 NumPy for Data Science
Operations on Numpy arrays

# Operations on Numpy arrays

## Arithmetic operators

In [ ]:
1. Arithmetic operators

    Numpy allows you to perform mathematical operations on arrays in an optimized way.

            Applying one of the basic arithmetic operations (/, *, -,+,**) between an array and a value will apply the operation to each of the elements of the array.

            It is also possible to perform an arithmetic operation between two arrays. This will apply the operation between each pair of elements.

        # Creation of two arrays with 2 values
        a = np.array([4, 10])
        b = np.array([6, 7])

        # Multiplication between two arrays
        print(a * b)
        >>> [24, 70]

    (a) Import the package numpy under the name np.

    (b) Create an array of dimensions 10x4 filled with ones.

    (c) Using a for loop and the enumerate function, multiply each row by its index. In order to modify the matrix,
    it must be accessed through indexing.


In [22]:
import numpy as np

X = np.ones((3,2))

for n, arr in enumerate(X):
    print(n, arr)

0 [1. 1.]
1 [1. 1.]
2 [1. 1.]


In [23]:
# If the array of the value is bigger than 1 then compute 2 powers of value 
X = np.ones((10,4))
X = X * [i for i in range(4)]
print(X[:2])

for i, row in enumerate(X):
    for j in row:
        if j > 1:
            X[i,int(j)] **= 2
            
X

[[0. 1. 2. 3.]
 [0. 1. 2. 3.]]


array([[0., 1., 4., 9.],
       [0., 1., 4., 9.],
       [0., 1., 4., 9.],
       [0., 1., 4., 9.],
       [0., 1., 4., 9.],
       [0., 1., 4., 9.],
       [0., 1., 4., 9.],
       [0., 1., 4., 9.],
       [0., 1., 4., 9.],
       [0., 1., 4., 9.]])

In [24]:
# Insert your code here
import numpy as np

X = np.ones((10,4))

for n, arr in enumerate(X):
    print(n * arr)

[0. 0. 0. 0.]
[1. 1. 1. 1.]
[2. 2. 2. 2.]
[3. 3. 3. 3.]
[4. 4. 4. 4.]
[5. 5. 5. 5.]
[6. 6. 6. 6.]
[7. 7. 7. 7.]
[8. 8. 8. 8.]
[9. 9. 9. 9.]


In [25]:
#original cozum 
import numpy as np

M = np.ones((10, 4))

# For each row of the matrix M
for i, row in enumerate(M):
    # We multiply the row by its index
    M[i,:] = row*i
    # Alternatively M[i,:]* = i
    
print(M)

[[0. 0. 0. 0.]
 [1. 1. 1. 1.]
 [2. 2. 2. 2.]
 [3. 3. 3. 3.]
 [4. 4. 4. 4.]
 [5. 5. 5. 5.]
 [6. 6. 6. 6.]
 [7. 7. 7. 7.]
 [8. 8. 8. 8.]
 [9. 9. 9. 9.]]


In [ ]:
As explained above, the * operator allows you to compute an element-wise product between arrays.

For example:

(5310)∗(2048)=(10040)

The matrix product, in the mathematical sense of the term, can be performed using the dot method of a numpy array:

# Creation of two arrays of size 2x2
M = np.array([[5, 1],
              [3, 0]])

N = np.array([[2, 4],
              [0, 8]])

# Matrix product between the two arrays
print(M.dot(N))
>>> [[10, 28]
>>>  [6, 12]]

Indeed, if we recall the matrix product:

𝑀=([5, 1],
    [3, 0]),
𝑁=([2, 4],
    [0, 8])

𝑀𝑁=(5310)(2048)=((5∗2)+(1∗0)(3∗2)+(0∗0)(5∗4)+(1∗8)(3∗4)+(0∗8))=[[10, 28],
                                                                 [ 6, 12]])
Let's consider the following matrix:

𝐴=(1−1−11)

    (d) Define a function named powerA taking as argument an integer n greater than 1. This function must compute and return 𝐴^𝑛

    (according to matrix product).

    (e) Calculate and display 𝐴^2, 𝐴^3 and 𝐴^4. Can you guess a general formula for 𝐴^𝑛?

In [26]:
M = np.array([[5, 1],
              [3, 0]])


N = np.array([[2, 4],
              [0, 8]])



def powerA(n, A, B):

    for i in range(n):
        at = A @ B
        A = A.dot(B)
    return A, at         


powerA(1, M, N)

(array([[10, 28],
        [ 6, 12]]),
 array([[10, 28],
        [ 6, 12]]))

In [27]:
# original cozum
def powerA(n):
    # A is initialized to the identity matrix
    A = np.array([[1, 0],
                  [0, 1]])
    
    # This matrix B will be used to calculate the powers of A
    B = np.array([[1, -1],
                  [-1, 1]])
    
    # We multiply A by B n times to get A**n
    for i in range(n):
        A = A.dot(B)
        
    return A

print ("A**2: \n", powerA(2), "\n")
print ("A**3: \n", powerA(3), "\n")
print ("A**4: \n", powerA(4), "\n")

print ("A general formula of A**n is given by:")
print ("[2**(n-1), -2**(n-1)]")
print ("[-2**(n-1), 2**(n-1)]")

A**2: 
 [[ 2 -2]
 [-2  2]] 

A**3: 
 [[ 4 -4]
 [-4  4]] 

A**4: 
 [[ 8 -8]
 [-8  8]] 

A general formula of A**n is given by:
[2**(n-1), -2**(n-1)]
[-2**(n-1), 2**(n-1)]


In [ ]:
In a two-dimensional plane, rotations around the origin are represented by the matrices of the form:

𝐴(𝜃)=(cos(𝜃) −sin(𝜃)
     sin(𝜃)  cos(𝜃))
where 𝜃 defines the angle of the rotation in radians. Thus, the rotation of a point with coordinates 𝑥=(𝑥1𝑥2) is calculated thanks to the formula 𝑥̃ =𝐴(𝜃)𝑥

    (f) Define a function named rotation_matrix taking as argument a number 𝜃

(theta) and returning the associated 𝐴(𝜃) matrix. You can calculate the cos and sin

    functions using the np.cos andnp.sin functions of numpy.

    (g) Let 𝑥=(1
                1)

be a point. Calculate and display 𝐴(𝜋)𝑥, which is equivalent to rotating 180º around the origin. You have access to the constant 𝜋

    with the np.pi instruction.

    (h) Show that 𝐴(𝜋4)𝐴(3𝜋4)𝑥=𝐴(𝜋)𝑥

    .

    (i) Generally speaking, for any angle, 𝐴(𝜃1)𝐴(𝜃2)𝑥=𝐴(𝜃1+𝜃2)𝑥

. Why is this the case?

In [30]:
# Insert your code here

def rotation_matrix(theta, X):
    Y = np.array([[np.cos(theta), -np.sin(theta)],
                  [np.sin(theta), np.cos(theta)]])
    return Y.dot(X)

#g)
x = np.array([1,1])

x_pi = rotation_matrix(np.pi, x)

print(x, x_pi )

#h)
a_pi_4 = rotation_matrix(np.pi/4, x)
a_3pi_4 = rotation_matrix(3*np.pi/4, x)

print(a_pi_4.dot(a_3pi_4), x_pi)

[1 1] [-1. -1.]
0.0 [-1. -1.]


In [31]:
# Insert your code here

def rotation_matrix(theta):
    Y = np.array([[np.cos(theta), -np.sin(theta)],
                  [np.sin(theta), np.cos(theta)]])
    return Y

#g)
x = np.array([1,1])

x_pi = rotation_matrix(np.pi)

print(x, x_pi.dot(x))

#h)
x = np.array([1,1])
a_pi_4 = rotation_matrix(np.pi/4)
a_3pi_4 = rotation_matrix(3*np.pi/4)

print(x, a_pi_4.dot(a_3pi_4.dot(x)), "\n")

#i)
pi = 100*np.pi
pi_2 = 200*np.pi

a_theta1 = rotation_matrix(pi)
a_theta2 = rotation_matrix(pi_2)
a_sum = rotation_matrix(pi + pi_2)

print("a_theta1 \n\n",a_theta1, "\n a_theta2 \n\n", a_theta2, "\n a_sum \n\n", a_sum, "\n")
print(a_theta1.dot(a_theta2.dot(x)))
print(a_sum.dot(x))

[1 1] [-1. -1.]
[1 1] [-1. -1.] 

a_theta1 

 [[ 1.00000000e+00 -1.96438672e-15]
 [ 1.96438672e-15  1.00000000e+00]] 
 a_theta2 

 [[ 1.00000000e+00 -3.92877345e-15]
 [ 3.92877345e-15  1.00000000e+00]] 
 a_sum 

 [[ 1.00000000e+00  5.09502587e-14]
 [-5.09502587e-14  1.00000000e+00]] 

[1. 1.]
[1. 1.]


In [29]:
#original cozum
#????????

# First question
def rotation_matrix(theta):
    A = np.array([[np.cos(theta), -np.sin(theta)],
                  [np.sin(theta), np.cos(theta)]])
    
    return A

# Second question
x = np.array([1, 1])
A_pi = rotation_matrix(np.pi)

print("x =", x)
print("A(pi)x =", A_pi.dot(x))

# Third question
A_pi_4 = rotation_matrix(np.pi/4)
A_3pi_4 = rotation_matrix(3*np.pi/4)

print("A(pi/4) A(3pi/4) x =", A_pi_4.dot(A_3pi_4.dot(x)))

# Fourth question
print("\n")
print("Intuitively, A(theta_1) A(theta_2) = A(theta_1 + theta_2) because applying a rotation of angle theta_1 then" )
print("applying another rotation of angle theta_2 is exactly the same as applying a rotation whose angle is the sum of the two.")

x = [1 1]
A(pi)x = [-1. -1.]
A(pi/4) A(3pi/4) x = [-1. -1.]


Intuitively, A(theta_1) A(theta_2) = A(theta_1 + theta_2) because applying a rotation of angle theta_1 then
applying another rotation of angle theta_2 is exactly the same as applying a rotation whose angle is the sum of the two.


## Broadcasting between a matrix and a value

In [ ]:
2. Broadcasting between a matrix and a value

    When performing an operation between elements of different dimensions, Numpy performs what is called Broadcasting to understand the operation and execute it.

    The term broadcasting is used because one of the arrays is "broadcasted" into an array of larger dimensions so that the two arrays have compatible dimensions. This definition will be illustrated below.

    In this section, we will try to understand numpy's broadcasting rules in the following cases:

        Operation between a matrix and a constant
        Operation between a matrix and a vector

    An arithmetic operation such as the sum between a matrix and a constant does not make mathematical sense. With Numpy, the broadcasting rule in this case is to sum the constant to each term of the matrix.

    𝑀=(3−21125),𝑐=10

𝑀+𝑐=(3+10−2+101+101+102+105+10)=(13811111215)

What really happens is that the constant 𝑐
is broadcasted into a matrix 𝐶 with the same dimensions as 𝑀

:

𝑐⟶broadcasting𝐶=(𝑐𝑐𝑐𝑐𝑐𝑐)

Thus, 𝑀+𝐶

    is mathematically well defined and can be computed with basic operations.



## Broadcasting between a matrix and a vector

In [1]:
3. Broadcasting between a matrix and a vector

    Similarly, numpy allows us to perform arithmetic operations between a matrix and a vector. However, there are some constraints which determine whether the vector can be broadcasted into a matrix with compatible dimensions.

    In order to determine if the dimensions of the vector and the matrix are compatible, numpy will compare each dimension of the two arrays and determine if:

        the dimensions are equal.
        one of the dimensions is equal to 1.

    If for each dimension, one of these conditions is verified, then the dimensions are compatible and the operation has been understood. Otherwise, a ValueError: operands could not be broadcast together error will be displayed.

    Let us consider the following objects :

    𝑀=(3−21125),𝑣=(25)

Do 𝑀
and 𝑣

have compatible dimensions for broadcasting?

𝑀
is a 2x3 dimensional matrix. 𝑣 is a vector with 2 elements, but numpy will instead see 𝑣

as a matrix of dimensions 2x1, that is, a matrix with two rows and one column.

The first dimension of 𝑀
and 𝑣 is equal to 2

. They are equal so the compatibility condition is verified for this dimension.

The second dimension of 𝑀
is equal to 3 and that of 𝑣

is equal to 1. The compatibility condition is still verified because one of the dimensions is equal to 1.

Therefore 𝑀
and 𝑣

have compatible dimensions for broadcasting.

The vector 𝑣
will then be broadcasted along the axis where the dimension of 𝑣 is equal to 1. In our case, it is the axis of the columns. The broadcasting of 𝑣

will therefore be given by:

𝑣=(25)⟶broadcasting𝑉=[𝑣𝑣𝑣]=(252525)

The result of 𝑀∗𝑣

will then be given by:

𝑀∗𝑣⟶broadcasting𝑀∗𝑉=(3∗2−2∗51∗21∗52∗25∗5)=(6−1025425)

Now suppose we have a line vector 𝑢=(34)

.

For numpy, this vector has dimensions 1x2 (one row and 2 columns). The vectors 𝑢
and 𝑣

are compatible for broadcasting because on each axis one of the vectors has a dimension equal to 1.

How and on which object is the broadcasting carried out in this case?

The broadcasting will be carried out on the two vectors and the resulting matrix of the broadcasting will have the largest dimension between the two vectors:

𝑣=(25)⟶broadcasting𝑉=(2525)

and

𝑢=(34)⟶broadcasting𝑈=(3344)

Thus, the result of 𝑣+𝑢

is given by:

𝑣+𝑢⟶broadcasting=(25)+(34)𝑉+𝑈=(2525)+(3344)=(5869)

    These rules allow us to understand and predict the result of an operation between two arrays which do not have the same shape. They will be useful for the following exercise:

    Min-Max normalization is a method that is used to rescale the variables of a database to the interval [0,1]

.

Assume our database contains 3 individuals and 2 variables:

        Jacques: 24 years old, height of 1.88m.

        Mathilde: 18 years old, height of 1.68m.

        Alban: 14 years old, height of 1.65m.

This data can be represented by the matrix:

𝑋=2418141.881.681.65

Each row corresponds to an individual, and each column corresponds to a variable. This format is the standard format for databases.

We want to compare the age differences with the height differences between individuals. However, the variables in this database do not have the same scale. We have to use Min-Max normalization so that the variables have the same scale.

We denote by 𝑋𝑖,𝑗
the value of the variable 𝑗 for the individual 𝑖 and 𝑋:,𝑗 the column of the variable 𝑗

.

Min-Max normalization will produce a new matrix 𝑋̃ 
such that for each entry of the 𝑋

matrix:

𝑋̃ 𝑖,𝑗=𝑋𝑖,𝑗−min(𝑋:,𝑗)max(𝑋:,𝑗)−min(𝑋:,𝑗)

Thus, to implement Min-Max normalization :

        For each 𝑋:,𝑗

column, compute min(𝑋:,𝑗) and max(𝑋:,𝑗)

    .

    For each element 𝑋𝑖,𝑗

in the column, compute 𝑋̃ 𝑖,𝑗

        .

By default, a for loop on 𝑋 will cycle through the lines of 𝑋. 
In order to browse the columns of 𝑋, you can browse the rows of the transposed matrix of 𝑋, which we denote by 𝑋𝑇

.

𝑋𝑇=(241.88181.68141.65)

The transposition of an array is obtained with its T attribute: 𝑋𝑇

    =X.T.

    (a) Define a function named normalization_min_max taking as argument a matrix 𝑋 and which will return 𝑋̃ 

    (b) Apply Min-Max normalization on 𝑋 . You should get the matrix to two decimal places:

X = np.array([[1, 0.4, 0],
              [1, 0.13, 0]])

In [32]:
# Insert your code here

def normalization_min_max(X):
    if X.ndim == 1:
        l2 = []
        for i in X:
            new_i = (i - min(X)) / (max(X) - min(X))
            l2.append(round(new_i, 2))
        return l2
    else:
        X = X.T
        for i, row in enumerate(X):
            mi = min(row)
            ma = max(row)
            for j, value in enumerate(row):
                new_value = (value - mi) / (ma - mi)
                X[i,j] = round(new_value, 2)

        return X.T

l = np.array([1,2,3,4])

X = np.array([[1, 0.4, 0],
              [1, 0.13, 0]])

y = np.array([[24, 1.88],
              [18, 1.68],
              [14, 1.65]])
normalization_min_max(l)
normalization_min_max(y)
#normalization_min_max(X) 

array([[1.  , 1.  ],
       [0.4 , 0.13],
       [0.  , 0.  ]])

In [33]:
# original cozum
def normalization_min_max(X):
    # Initialization of X_tilde
    X_tilde = np.zeros(shape = X.shape)
    
    # For each column of X
    for j, column in enumerate(X.T):
        # Initialization of the minimum and maximum of the column
        min_Xj = column[0]
        max_Xj = column[0]
        
        # For each value in the column
        for value in column:
            # If the value is SMALLER than the min
            if value < min_Xj:
                # We overwrite the min with this value
                min_Xj = value
            
            # If the value is GREATER than the max
            if value > max_Xj:
                # We overwrite the max with this value
                max_Xj = value
                
        # We can now calculate X_tilde for this column
        # Broadcasting allows us to do this without a for loop
        X_tilde[:, j] = (X[:, j] - min_Xj)/(max_Xj - min_Xj)
            
    return X_tilde
        

X = np.array([[24, 1.88],
              [18, 1.68],
              [14, 1.65]])

X_tilde = normalization_min_max(X)

print(X_tilde)

[[1.         1.        ]
 [0.4        0.13043478]
 [0.         0.        ]]


## Statistical methods

In [ ]:
4. Statistical methods

    In addition to common math operations, numpy arrays also have several methods for more complex operations on arrays.

    One of the most used operations is the computation of an average using the mean method of an array:

    A = np.array([[1, 1, 10],
                  [3, 5, 2]])

    # Computation of the mean over ALL the values of X
    print(A.mean())
    >>> 3.67

    # Computation of the mean of each COLUMN of X
    print(A.mean(axis = 0))
    >>> [2, 3, 6]

    # Computation of the mean of each ROW of X
    print(A.mean(axis = 1))
    >>> [4, 3.33]

    The argument axis determines which dimension will be scanned to compute the mean:

            axis = 0 means that the dimension scanned will be that of rows, which means that the result will be the average of each column.

            axis = 1 means that the dimension scanned will be that of columns, which means that the result will be the average of each row.

    The axis argument is very often used for operations on matrices, and not only for Numpy. It is very important to understand its effect.

    There are other statistical methods that behave like the mean method, such as:

            sum: Computes the sum of the elements of an array.

            std: Computes the standard deviation.

            min: Finds the minimum value among the elements of an array.

            max: Finds the maximum value among the elements of an array.

            argmin: Returns the index of the minimum value.

            argmax: Returns the index of the maximum value.

    These methods are useless for databases if you do not provide a value for the axis argument.

    In general, we will use the value axis = 0 to get the result for each column, that is, for each variable in the database.

    Thus, we can calculate the Min-Max normalization very quickly using the min and max methods along with broadcasting:

    X_tilde = (X - X.min(axis = 0))/(X.max(axis = 0) - X.min(axis = 0))

    print (X_tilde)
    >>> [[1, 1]
    >>>  [0.4, 0.13043478]
    >>>  [0, 0]]

The Mean Squared Error is a metric to quantify the prediction error obtained by a regression model. This notion will be seen in more detail later in your training.

The formula for the mean squared error, abbreviated by MSE

, is calculated with the following formula:

MSE=1𝑛∑𝑖=1𝑛(𝑦̂ 𝑖−𝑦𝑖)2

where:

        𝑦̂ 

and 𝑦 are vectors with length 𝑛

    .

    𝑦̂ 

is given by the matrix product between a 𝑋 matrix and a regression vector 𝛽, ie:
𝑦̂ =𝑋𝛽

In the case of linear regression, the goal of the mean squared error is to find the regression vector 𝛽

which minimizes this error.

    (a) Define a function named mean_squared_error taking as argument a matrix X
    , a vector beta and a vector y and which, without a for loop, returns the associated mean squared error.


In [34]:
# original cozum
def mean_squared_error(X, beta, y):
    # Computation of ^y
    y_hat = X.dot(beta)
    
    # Computation of (^y_i - y_i)**2
    mse = (y_hat - y)**2
    
    # MSE
    mse = mse.mean()
    
    return mse

In [ ]:
Our database contained 3 individuals and 2 variables:

        Jacques: 24 years old, height 1.88m.

        Mathilde: 18 years old, height 1.68m.

        Alban: 14 years old, height 1.65m.

We will try to find a model able to predict the height of an individual based on his age. Thus, we define:
𝑋=241814

𝑦=1.881.681.65

Our goal will be to find an optimal 𝛽∗
such that:
𝑦≈𝑋𝛽∗

    (b) For beta taking the values 0.01, 0.02, ..., 0.13, 0.14 and 0.15, compute the associated MSE

    using the previously defined mean_squared_error function. Store the values in a list.

    To create the list [0.01, 0.02, ..., 0.13, 0.14, 0.15], you can use the np.linspace function which has a signature similar to the range function:

    print(np.linspace(start = 0.01, stop = 0.15, num = 15))
    >>> [0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1, 0.11, 0.12, 0.13, 0.14, 0.15]

    The num argument allows you to define the desired number of elements between start and stop. It is not the step between two consecutive values.


In [35]:
X = np.array([24,
              18,
              14])

y = np.array([1.88,
              1.68,
              1.65])

# Insert your code here


lst = np.linspace(0.01, 0.15, 15)
result = []
for beta in  lst:
    result.append([mean_squared_error(X, beta, y), beta])

#print(result)
print("Mininmun MSE and Optimal Beta :",min(result))

Mininmun MSE and Optimal Beta : [0.07803333333333334, 0.08999999999999998]


In [36]:
# original cozum
X = np.array([24,
              18,
              14])

y = np.array([1.88,
              1.68,
              1.65])

# List containing the mse
errors = []

# List containing the betas to be tested
betas = np.linspace(start = 0.01, stop = 0.15, num = 15)

# For all the values of beta
for beta in betas:
    # Compute the associated MSE
    errors.append(mean_squared_error(X, beta, y))

In [ ]:
(c) Convert the list containing the MSE

    's to a numpy array.

    (d) Determine the 𝛽∗

that minimizes the MSE using the argmin method.

In [37]:
# Insert your code here

errs_arr = np.array(errors)
print("Array of MSE : \n", errs_arr, "\n")

min_err_index = errs_arr.argmin()
print("Min MSE index :", min_err_index, "\n")

print("Minimum MSE = ",errs_arr[min_err_index], "\n")
print("Optimal Beta = ", betas[min_err_index])

Array of MSE : 
 [2.40656667 1.85976667 1.38603333 0.98536667 0.65776667 0.40323333
 0.22176667 0.11336667 0.07803333 0.11576667 0.22656667 0.41043333
 0.66736667 0.99736667 1.40043333] 

Min MSE index : 8 

Minimum MSE =  0.07803333333333334 

Optimal Beta =  0.08999999999999998


In [38]:
# original cozum
# Array containing the MSE for each beta
errors = np.array(errors)

# List containing the betas that have been tested
betas = np.linspace(start = 0.01, stop = 0.15, num = 15)

# Index of the beta that minimizes the MSE 
index_beta_optimal = errors.argmin()

# Optimal beta 
beta_optimal = betas[index_beta_optimal]

print("The optimal beta is:", beta_optimal)

The optimal beta is: 0.08999999999999998


In [ ]:
e) What are the heights predicted by this optimal 𝛽∗? The heights predicted by the model are given by the vector 𝑦̂ =𝑋𝛽∗

    .

(f) Compare the predicted heights to the actual heights of the individuals. 
For example, you can compute the average absolute difference between the predicted and true values using the absolute value (np.abs).


In [39]:
# Insert your code here

y_predict = X.dot(beta_optimal)
print("Predicted heights : ",y_predict)


print("Real heights      : ", y)

errors_ = np.abs(y - y_predict)

print("Erros             : ", errors_)

print("Average of errors : ", errors_.mean())


Predicted heights :  [2.16 1.62 1.26]
Real heights      :  [1.88 1.68 1.65]
Erros             :  [0.28 0.06 0.39]
Average of errors :  0.2433333333333334


In [40]:
y_hat = X.dot(beta_optimal)
print("Predicted heights: \n", y_hat)

print("\n Real heights: \n", y)

print("\n The model makes an average mistake of", np.abs(y - y_hat).mean(), "metres.")

# The predicted heights are incorrect but approximately very close to the real sizes.

Predicted heights: 
 [2.16 1.62 1.26]

 Real heights: 
 [1.88 1.68 1.65]

 The model makes an average mistake of 0.2433333333333334 metres.


# Introduction to DataFrames 

In [ ]:
Introduction

    The pandas module has been developed to provide Python with the tools necessary to manipulate and analyze large volumes of data.

    Pandas introduces the DataFrame class, an array-like data structure that offers more advanced data manipulation and exploration than NumPy arrays.

    The main features of pandas are:

            data recovery from files (CSV, Excel tables, etc.)

            handling this data (deletion / addition, modification, statistical visualization, etc.).

    This notebook aims at:

            Understanding the format of a DataFrame.

            Creating a first Dataframe.

            Carrying out a first exploration of a dataset using the DataFrame class.

    (a) Import the pandas module under the name pd.


In [ ]:
# Insert your code here
import pandas as pd

## Format of a DataFrame

In [ ]:
1. Format of a DataFrame

    A DataFrame is in the form of a matrix whose rows and columns each have an index. Typically, columns are indexed by name and rows by unique identifiers.

    A DataFrame is used to store a database. The different entries in the database (individuals, animals, objects, etc.) are the different lines and their features are the different columns:
    	Name 	Gender 	Height 	Age
    0 	Robert 	M 	174 	23
    1 	Mark 	M 	182 	40
    2 	Aline 	F 	169 	56

            The DataFrame above groups together information on 3 individuals: the DataFrame therefore has 3 lines.

            For each of these individuals, there are 4 variables (name, gender, height and age) : therefore, the DataFrame has 4 columns.

    The column containing the numbering of the lines is called the index and is not managed in the same way as other columns of the DataFrame.

    The index can be set by default (will follow the row numbering), defined with one (or several) of the columns of the DataFrame or even defined with a list that we specify.

    Example: Default indexing (line numbering), you don't have to specify anything :
    	Name 	Gender 	Height 	Age
    0 	Robert 	M 	174 	23
    1 	Mark 	M 	182 	40
    2 	Aline 	F 	169 	56

    Example: Indexing by the column 'Name':
    	Gender 	Height 	Age
    Robert 	M 	174 	23
    Mark 	M 	182 	40
    Aline 	F 	169 	56

    Example: Indexing by the list ['person_1', 'person_2', 'person_3']:
    	Name 	Gender 	Height 	Age
    person_1 	Robert 	M 	174 	23
    person_2 	Mark 	M 	182 	40
    person_3 	Aline 	F 	169 	56

    We will detail later how to define the index when creating a DataFrame.

    The DataFrame class has several advantages over aNumpy array:

            Visually, a DataFrame is much more readable thanks to more explicit column and row indexing.

            Within the same column the elements are of the same type but from one column to another, the type of the elements may vary, which is not the case of Numpy arrays which only support data of the same type.

            The DataFrame class contains more methods for handling and preprocessing databases, while NumPy specializes instead in optimized computation.



## Creation of a DataFrame: from a NumPy array

In [ ]:
2. Creation of a DataFrame: from a NumPy array

    It is possible to directly create a DataFrame from a NumPy array using the DataFrame() constructor. The disadvantage of this method is that it is not very practical and the data type is necessarily the same for all the columns.

    Let's take a closer look at the header of this constructor.

    pd.DataFrame(data, index, columns, ...)

            The data parameter contains the data to be formatted (NumPy array, list, dictionary or another DataFrame).

            The index parameter, if specified, must be a list containing the indices of the entries.

            The columns parameter, if specified, must be a list containing the name of the columns.

    For other parameters, you can consult the Python documentation.

    Example:

    # Creation of a NumPy array with 3 rows and 4 columns
    array = np.array ([[1, 2, 3, 4],
                       [5, 6, 7, 8],
                       [9, 10, 11, 12]])

    # Instantiation of a DataFrame
    df = pd.DataFrame (data = array, # The data to format
                       index = ['i_1', 'i_2', 'i_3'], # The indices of each entry
                       columns = ['A', 'B', 'C', 'D']) # The name of the columns

    This produces the following DataFrame:
    	A 	B 	C 	D
    i_1 	1 	2 	3 	4
    i_2 	5 	6 	7 	8
    i_3 	9 	10 	11 	12

## Creation of a DataFrame: from a dictionary

In [ ]:
3. Creation of a DataFrame: from a dictionary

    Another way to create a DataFrame is to use a dictionary. Thanks to this technique, the columns can be of different type and their names are already given when creating the DataFrame.

    Example:

    # Creation of a dictionary
    dictionary = {'A': [1, 5, 9],
                  'B': [2, 6, 10],
                  'C': [3, 7, 11],
                  'D': [4, 8, 12]}

    # Instantiation of a DataFrame
    df = pd.DataFrame (data = dictionary,
                       index = ['i_1', 'i_2', 'i_3'])

    This produces the same DataFrame as before:
    	A 	B 	C 	D
    i_1 	1 	2 	3 	4
    i_2 	5 	6 	7 	8
    i_3 	9 	10 	11 	12

The manager of a grocery store has the following stock of food products:

    100 jars of honey with an expiration date of 08/10/2025 and worth €2 each.

    55 packets of flour expiring on 09/25/2024 each costing € 3.

    1800 bottles of wine costing € 10 per unit and expiring on 10/15/2023.

    (a) From a dictionary, create and display a DataFrame df that contains for each product:

            Its name.
            Its expiration date.
            Its quantity.
            Its price per unit.

You will choose relevant column names and the index will be the default one (in this case we do not specify the index parameter).

In [42]:
# Insert your Code

dictionary = {"Product"          : ['honey', 'flour', 'wine'],
              "Expiration date"  : ['10/08/2025', '25/09/2024', '15/10/2023'],
              "Quantity"         : [100, 55, 1800], 
              "Price per unit"   : [2, 3, 10]}

df = pd.DataFrame(dictionary)

df

Product Expiration date  Quantity  Price per unit
0   honey      10/08/2025       100               2
1   flour      25/09/2024        55               3
2    wine      15/10/2023      1800              10

## Creation of a DataFrame: from a data file

In [ ]:
4. Creation of a DataFrame: from a data file

    Most often a DataFrame is created directly from a file containing the data of interest. The file's format can be a CSV, Excel, txt, etc.

    The most common format is the CSV format, which stands for Comma-Separated Values and denotes a spreadsheet-like file whose values are separated by commas.

    Here is an example:

    A, B, C, D,
    1, 2, 3, 4,
    5, 6, 7, 8,
    9, 10, 11, 12

    In this format:

            The first line contains the name of the columns, but sometimes the name of the columns is not filled in.

            Each line corresponds to an entry in the database.

            The values are separated by a separator character. In this example, it is ',' but it could be a ';'.

    To import the data into a DataFrame, we need to use the read_csv function of pandas whose header is as follows:

    pd.read_csv(filepath_or_buffer, sep = ',', header = 0, index_col = 0 ...)

    The essential arguments of the pd.read_csv function to know are:

            filepath_or_buffer: The path of the .csv file relative to the execution environment.
                If the file is in the same folder as the Python environment, just fill in the name of the file.
                This path must be entered in the form of character string.

            sep: The character used in the .csv file to to separate the different columns.
                This argument must be specified as character.

            header: The number of the row that contains the names of the columns.
                If for example the column names are entered in the first line of the .csv file, then we must specify header = 0.
                If the names are not included, we will put header = None.

            index_col: The name or number of the column containing the indices of the database.
                If the database entries are indexed by the first column, you will need to fill in index_col = 0.
                Alternatively, if the entries are indexed by a column which bears the name "Id", we can specify index_col = "Id".

    This function will return an object of type DataFrame which contains all the data of the file.

    (a) Load the data contained in the file transactions.csv into aDataFrame named transactions:

            The file is located in the same folder as the environment of this notebook.
            Columns are separated by commas.
            The names of the columns are in the first line of the file.
            The rows of the database are indexed by the "transaction_id" column which is also the first column.



In [ ]:
# insert your code

# You can directly specify the name of the column containing the indices

transactions = pd.read_csv(filepath_or_buffer = 'transactions.csv', # file path
                           sep = ',',                               # character separating values
                           header = 0,                              # number of the row containing column names
                           index_col = 'transaction_id')            # name of the column that indexes the entries


# You can also directly enter the number of the column that indexes the entries

transactions = pd.read_csv(filepath_or_buffer = 'transactions.csv',
                           sep = ',',
                           header = 0,
                           index_col = 0) # number of the column that indexes the entries

# We loaded the transactions.csv file in theDataFrame transactions which gathers a history of transactions carried out between 2011 and 2014. 
#In the next section, we will study this dataset.

## First exploration of a dataset using the DataFrame class

In [ ]:
5. First exploration of a dataset using the DataFrame class

    The rest of this notebook briefly presents the main methods of the DataFrame class which will allow us to do a quick analysis of our data set, that is:

            Having a brief overview of the data (head method,columns and shape attributes).

            Selecting values in the DataFrame (loc and iloc methods).

            Carrying out a quick statistical study of our data (describe and value _counts methods)

    As a reminder, to apply a method to an object in Python (such as a DataFrame for example), you must add the method as a suffix of the object. Example: my_object.my_method()


## Visualization of a DataFrame: head method, columns and shape attributes

In [ ]:
6. Visualization of a DataFrame: head method, columns and shape attributes

        It is possible to have a preview of a dataset by displaying only the first lines of the DataFrame.

    For that, we must use the head() method, specifying as an argument the number of lines that we want to display (by default 5).

    It is also possible to preview the last lines using the tail() method which is applied in the same way:

    # Display of the first 10 lines of my_dataframe
    my_dataframe.head(10)

    (a) Display the first 20 lines of the transactions DataFrame.


In [ ]:
# Insert your code here
transactions.head(20)

In [ ]:
# (b) Display the last 10 lines of the transactions DataFrame.

In [ ]:
# Insert your code here
transactions.tail(10)

In [ ]:
     	A 	B 	C 	D
    i_ 1 	1 	2 	3 	4
    i _2 	5 	6 	7 	8
    i_ 3 	9 	10 	11 	12

    # Display of df DataFrame columns
    print(df.columns)
    >>> ['A', 'B', 'C', 'D']

    The list of the column names can be used to iterate over the columns of a DataFrame within a loop.

    It can be interesting to know how many transactions (rows) and how many features (columns) the dataset contains.

    For this we will use the shape attribute of the DataFrame class which displays the dimensions of our DataFrame in the form of a tuple (number of rows, number of columns):

    # Display the dimensions of df
    print (df.shape)
    >>> (3,4)

    (c) Display the dimensions of the DataFrame transactions as well as the name of the 5th column. Remember that in Python the indices start from 0.


In [ ]:
# Insert your code here
print(transactions.shape)

transactions.columns[4]

## Selecting columns from a DataFrame

In [ ]:
7. Selecting columns from a DataFrame

    Extracting columns from a DataFrame is almost identical to extracting data from a dictionary.

    To extract a column from a DataFrame, all we have to do is enter between brackets the name of the column to extract. To extract several columns, we must enter between brackets the list of the names of the columns to extract:

    # Display of the 'cust_id' column
    print(transactions['cust_id'])

    # Extraction of 'cust_id' and 'Qty' columns from transactions
    cust_id_qty = transactions[["cust_id", "Qty"]]

    cust_id_qty is a new DataFrame containing only the 'cust_id' and 'Qty' columns.

    The display of the first 3 lines of cust_id_qty yields:



    transactions_id 	cust_id 	Qty
    80712190438 	270351 	-5
    29258453508 	270384 	-5
    51750724947 	273420 	-2

    When we prepare a dataset for later use, it is better to separate the categorical variables from the quantitative variables:

            A categorical variable is a variable that takes only a finite number of modalities.

            The categorical variables of the DataFrame transactions are: ['cust_id', 'tran_date', 'prod_subcat_code', 'prod_cat_code', 'Store_type'].

            A quantitative variable is a variable that measures a quantity that can take an infinite number of values.

            The quantitative variables of transactions are: ['Qty', 'Rate', 'Tax', 'total_amt'].

    This distinction is made because some basic operations like calculating an average only make sense for quantitative variables.

    (a) In a DataFrame named cat_vars, store the categorical variables of transactions.

    (b) In a DataFrame named num_vars, store the quantitative variables of transactions.

    (c) Display the first 5 lines of each DataFrame.



In [ ]:
# insert your code

# Extraction of categorical variables
cat_var_names = ['cust_id', 'tran_date', 'prod_subcat_code', 'prod_cat_code' , 'Store_type']
cat_vars = transactions[cat_var_names]

# Extraction of quantitative variables
num_var_names = ['Qty', 'Rate', 'Tax', 'total_amt']
num_vars = transactions[num_var_names]

# Display of the first 5 lines of each DataFrame
print ("Categorical variables: \n")
print (cat_vars.head(), "\n \n")

print ("Quantitative variables: \n")
print (num_vars.head())

## Selecting rows of a DataFrame: loc and iloc methods

In [ ]:
8. Selecting rows of a DataFrame: loc and iloc methods

    To extract one or more rows from a DataFrame, we use the loc method. loc is a very special type of method because the arguments are filled in between square brackets and not between parentheses. Using this method is very similar to indexing lists.

    In order to retrieve the line of index i of a DataFrame, all we have to do is enter i as an argument of the loc method:

    # We retrieve the line of index 80712190438 of the num_vars DataFrame
    print(num_vars.loc[80712190438])

    >>                 Rate    Tax  total_amt
    >> transaction_id                         
    >> 80712190438    -772.0  405.3    -4265.3
    >> 80712190438     772.0  405.3     4265.3

    In order to retrieve several rows, we can either:

            Enter a list of indices.

            Enter a slice by specifying the start and end indices of the slice. To use slicing with loc, the indices must be unique, which is not the case for transactions.

    # We retrieve the rows at indices 80712190438, 29258453508 and 51750724947 from the transactions DataFrame
    transactions.loc[[80712190438, 29258453508, 51750724947]]

    loc can also take a column or list of columns as an argument in order to refine the data extraction:

    # We extract the columns 'Tax' and 'total_amt' from the rows at index 80712190438 and 29258453508
    transactions.loc[[80712190438, 29258453508], ['Tax', 'total_amt']]

    This instruction produces the following DataFrame:



    transaction_id 	Tax 	total_amt
    80712190438 	405.300 	-4265.300
    80712190438 	405.300 	4265.300
    29258453508 	785.925 	-8270.925
    29258453508 	785.925 	8270.925

    The iloc method is used to index a DataFrame exactly like a numpy array, that is to say by only filling in the numeric indices of the rows and columns. This allows the use of slicing without constraint:

    # Extraction of the first 4 rows and the first 3 columns of transactions
    transactions.iloc[0:4, 0:3]

    This instruction produces the following DataFrame:



    transaction_id 	cust_id 	tran_date 	prod_subcat_code
    80712190438 	270351 	28-02-2014 	1.0
    29258453508 	270384 	27-02-2014 	5.0
    51750724947 	273420 	24-02-2014 	6.0
    93274880719 	271509 	24-02-2014 	11.0

    If the row indexing is the one by default (row numbering), the loc and iloc methods are equivalent.





## Conditional indexing of a DataFrame

In [ ]:
9. Conditional indexing of a DataFrame

    As with Numpy arrays, we can use conditional indexing to extract rows from a Dataframe that meet a given condition.

    In the following illustration, we select the rows of the DataFrame df for which the column col 2 is equal to 3.


    There are two syntaxes for conditionally indexing a DataFrame:


    # We select the rows of the DataFrame df for which the column 'col 2' is equal to 3.
    df[df['col 2'] == 3]

    df.loc[df['col 2'] == 3]

    If we want to assign a new value to these entries, we must absolutely use the loc method.

    Indeed, indexing with the syntax df[df['col 2'] == 3] only returns a copy of these entries and does not provide access the memory location where the data is located.

The manager of the transactions listed in the transactions DataFrame wishes to have access to the identifiers of customers who have made an online purchase (i.e. in a "e-Shop") as well as the date of the corresponding transaction.

We have the following information about the columns of transactions:
Column name 	Description
'cust_id' 	The identifier of the customer
'Store_type' 	The type of store where the transaction took place
'tran_date' 	The date of the transaction

    (a) In a DataFrame named transactions_eshop, store the transactions that took place in an "e-Shop" type store.

    (b) In another DataFrame named transactions_id_date, store the customer identifiers and the transaction date of the transactions_eshop DataFrame.

    (c) Display the first 5 rows of transactions_id_date.

In [ ]:
# insert your code

# Creation of transactions_eshop by conditional indexing
transactions_eshop = transactions.loc[transactions['Store_type'] == 'e-Shop']

# Extraction of the 'cust_ id' and 'tran _date' columns
transactions_id_date = transactions_eshop[['cust_id', 'tran_date']]

# Display of the first 5 lines of transactions_id_date
transactions_id_date.head()

In [ ]:
Now, the manager would like to have access to the transactions carried out by the client whose identifier is 268819.

    (d) In a DataFrame named transactions_client_268819, store all transactions with client identifier 268819.

    (e) A column in a DataFrame can be iterated over with a loop exactly like a list (for value in df['column']:). Using a for loop on the 'total_amt' column, compute and display the total transaction amount for the client with identifier 268819.



In [ ]:
# Insert your code here

# Extraction of the transactions ofthe customer which identifier is 268819
transactions_client_268819 = transactions[transactions['cust_id'] == 268819]


# Computation of the total amount of transactions
total = 0

# For each amount in the column 'total_amt'
for amount in transactions_client_268819['total_amt']:
    # We sum the amounts
    total += amount
    
print(total)

# Second Way
transactions.loc[transactions.cust_id == 268819]['total_amt'].sum()

## Quick statistical study of the data in a DataFrame.

In [ ]:
10. Quick statistical study of the data in a DataFrame.

    The describe method of a DataFrame returns a summary of the descriptive statistics (min, max, mean, quantiles,...) of its quantitative variables. It is therefore a very useful tool for a first visualisation of the type and distribution of these variables.

    To analyse the categorical variables, it is recommended to start by using the value_counts method which returns the number of occurrences for each modality of these variables. The value_counts method cannot be used directly on a DataFrame but only on the columns of the DataFrame which are objects of the pd.Series class.

    (a) Use the describe method of the DataFrame transactions.

    (b) The quantitative variables of transactions are 'Qty', 'Rate', 'Tax' and total_amt'. By default, are the statistics produced by the describe method only computed on the quantitative variables?

    (c) Display the number of occurrences of each modality of the Store_type column using the value_counts method.



In [ ]:
# Insert your code here

transactions.describe()

transactions['Store_type'].value_counts()

In [ ]:


    The describe method computed statistics on the variables cust_id, prod_subcat_code and prod_cat_code while these are categorical variables.

    Of course, these statistics make no sense. The describe method has treated these variables as quantitative because the modalities they take are of numerical type.

    This is why it is necessary to pay attention to the results returned by the describe method and always take a step back to remember what the variables are reflecting.

    The manager wishes to make a quick report on the characteristics of the transactions DataFrame: in particular, he wants to know the average amount spent as well as the maximum quantity purchased.

    (d) What is the average total amount spent? We are interested in the 'total_amt' column of transactions.

    (e) What is the maximum quantity purchased? We will look at the 'Qty' column of transactions.



In [ ]:
# Insert your code here

print('average total amount spent :', transactions['total_amt'].mean())
print('maximum quantity purchased :', transactions['Qty'].max())

transactions.describe()

# Applying the describe method to the transactions DataFrame
transactions.describe()

# The average total amount spent is €2109.
# The maximum quantity purchased is 5. 

In [ ]:
Some transactions have negative amounts.

These are transactions that have been cancelled and refunded to the client. These amounts will disrupt the distribution of the amounts which gives us bad estimates of the mean and quantiles of the variable total_amt.

    (f) What is the average amount of transactions with positive amounts?



In [ ]:
# insert your code here

transactions[transactions['total_amt'] > 0].describe()

# the average amount of transactions with positive amounts is worth €2608 which is
# €500 more than we had before.

## Conclusion and recap

In [ ]:
11. Conclusion and recap

    The DataFrame class of the pandas module will be your favorite data structure when exploring, analysing and processing datasets and databases.

    In this brief introduction, you have learned to:

            Create a DataFrame from a numpy array and a dictionary using the pd.DataFrame constructor.

            Create a DataFrame from a .csv file using the pd.read_csv function.

            Display the first and last lines of a DataFrame using the head and tail methods.

            Select one or more columns of a DataFrame by entering their names in square brackets as in a dictionary.

            Select one or more lines of a DataFrame by filling in their index using the loc and iloc methods.

            Select the lines of a DataFrame that meet a specific condition using conditional indexing.

            Perform a quick statistical study of the quantitative variables of a DataFrame using the describe method.

    The dataset transactions we used is very clean. The variables are cleanly filled in and do not contain any missing value. In practice, this is rarely the case. This is why in the following notebook we will see how to clean datasets with pandas.



In [28]:
import pandas as pd
df= pd.read_csv('transactions.csv', index_col='transaction_id')
df['\ttran_date'] = df['\ttran_date'].apply(lambda x : x.replace('\t', ''))
df.rename(columns= lambda x : x.replace('\t', ''), inplace=True)
df

cust_id   tran_date  prod_subcat_code  prod_cat_code  qty  \
transaction_id                                                              
80712190438      270351  28-02-2014                 1              1   -5   
29258453508      270384  27-02-2014                 5              3   -5   
51750724947      273420  24-02-2014                 6              5   -2   
93274880719      271509  24-02-2014                11              6   -3   
51750724947      273420  23-02-2014                 6              5   -2   

                  rate      tax  total_amt  store_type  
transaction_id                                          
80712190438     -772.0  405.300  -4265.300           1  
29258453508    -1497.0  785.925  -8270.925           1  
51750724947     -791.0  166.110  -1748.110           2  
93274880719    -1363.0  429.345  -4518.345           1  
51750724947     -791.0  166.110  -1748.110           2

In [29]:
df['day'] = df['tran_date'].apply(lambda x : x.split('-')[0])
df['month'] = df['tran_date'].apply(lambda x : x.split('-')[1])
df['year'] = df['tran_date'].apply(lambda x : x.split('-')[2])
df

cust_id   tran_date  prod_subcat_code  prod_cat_code  qty  \
transaction_id                                                              
80712190438      270351  28-02-2014                 1              1   -5   
29258453508      270384  27-02-2014                 5              3   -5   
51750724947      273420  24-02-2014                 6              5   -2   
93274880719      271509  24-02-2014                11              6   -3   
51750724947      273420  23-02-2014                 6              5   -2   

                  rate      tax  total_amt  store_type day month  year  
transaction_id                                                          
80712190438     -772.0  405.300  -4265.300           1  28    02  2014  
29258453508    -1497.0  785.925  -8270.925           1  27    02  2014  
51750724947     -791.0  166.110  -1748.110           2  24    02  2014  
93274880719    -1363.0  429.345  -4518.345           1  24    02  2014  
51750724947     -791.0  166.110  -1748.110           2  23    02  2014

In [30]:
df['unit_price'] = df.apply(lambda row : row['total_amt']/row['qty'], axis = 1)
df

cust_id   tran_date  prod_subcat_code  prod_cat_code  qty  \
transaction_id                                                              
80712190438      270351  28-02-2014                 1              1   -5   
29258453508      270384  27-02-2014                 5              3   -5   
51750724947      273420  24-02-2014                 6              5   -2   
93274880719      271509  24-02-2014                11              6   -3   
51750724947      273420  23-02-2014                 6              5   -2   

                  rate      tax  total_amt  store_type day month  year  \
transaction_id                                                           
80712190438     -772.0  405.300  -4265.300           1  28    02  2014   
29258453508    -1497.0  785.925  -8270.925           1  27    02  2014   
51750724947     -791.0  166.110  -1748.110           2  24    02  2014   
93274880719    -1363.0  429.345  -4518.345           1  24    02  2014   
51750724947     -791.0  166.110  -1748.110           2  23    02  2014   

                unit_price  
transaction_id              
80712190438        853.060  
29258453508       1654.185  
51750724947        874.055  
93274880719       1506.115  
51750724947        874.055

In [39]:
date1 = df.tran_date.iloc[0]

'28-02-2014'

# Data Cleaning and Missing Values Management

In [ ]:
# Insert your code here
import pandas as pd

df = pd.read_csv('transactions.csv', sep=',', index_col='transaction_id')
df1 = df.copy()
df.head(10)

## Cleaning up a dataset

In [ ]:
1. Cleaning up a dataset

    In this part we will introduce the methods of the DataFrame class that are essential to clean a dataset. These methods can be grouped into three different categories :

            Duplicates management (duplicated and drop_duplicates methods)

            Modification of the elements of a DataFrame (replace, rename and astype methods)

            Operations on the values of a DataFrame (apply method and lambda functions)

Managing duplicates (duplicated and drop_duplicates methods)

    Duplicates are identical entries that appear more than once in a dataset.

    When we first discover a dataset it is very important to check up front that there are no duplicates. The presence of duplicates will generate errors in the computation of statistics or the plotting of graphs.

    Let df be the following DataFrame:
    	Age 	Gender 	Height
    Robert 	56 	M 	174
    Mark 	23 	M 	182
    Alina 	32 	F 	169
    Mark 	23 	M 	182

    The presence of duplicates is checked using the duplicated method of a DataFrame:

    # We identify the rows containing duplicates
    df.duplicated()

    >>> 0 False
    >>> 1 False
    >>> 2 False
    >>> 3 True

    This method returns Series object from pandas, which is equivalent to the column of a DataFrame. The Series object tells us for each row wether it is a duplicate.

    In this example, the result of the duplicated method informs us that the row with index 3 is a duplicate. Indeed, it is the exact copy of the row with index 1.

    Since the duplicated method returns an object of the Series class, we can apply the sum method to it in order to count the number of duplicates:

    # To calculate the sum of boolean values, we consider that True is worth 1 and False is worth 0.
    print(df.duplicated().sum())
    >>> 1

    The method of the DataFrame class used to remove duplicates is drop_duplicates. Its header is as follows:

    drop_duplicates(subset, keep, inplace)

            The subset parameter indicates the column(s) to consider in order to identify and remove duplicates. By default, subset = None namely we consider all the columns of the DataFrame.

            The keep parameter indicates which entry should be kept :

                    'first' : We keep the first occurrence.
                    'last': We keep the last occurrence.
                    False: We do not keep any occurrence.
                    By default, keep = 'first'.

            The inplace parameter (very common in the methods of the DataFrame class), specifies whether you modify directly the DataFrame (in this case inplace = True) or if the method returns a copy of the DataFrame (inplace = False). A method applied with the argument inplace = True is irreversible. By default, inplace = False.

    You have to be very careful when using the inplace parameter. A good practice is to forget this parameter and assign the DataFrame returned by the method to a new DataFrame.

    The keep parameter is the one that is most often specified. Indeed, a database can have duplicates created on different dates. We will then specify the value of the keep argument to keep only the most recent entries, for example.

    Let us go back to the df DataFrame :
    	Age 	Gender 	Height
    Robert 	56 	M 	174
    Mark 	23 	M 	182
    Alina 	32 	F 	169
    Mark 	23 	M 	182

    We illustrate df with the following illustration :

    We illustrate in the following examples the entries that are deleted by the drop_duplicates method depending on the value of the keep parameter:

    # We keep only the first occurrence of the duplicate
    df_first = df.drop_duplicates(keep = 'first')



    # We keep only the last occurrence of the duplicate
    df_last = df.drop_duplicates(keep = 'last')

    # We keep no duplicates
    df_false = df.drop_duplicates(keep = False)

    (a) How many duplicates are there in the transactions DataFrame ?



In [ ]:
# Counting the number of duplicates
duplicates = transactions.duplicated().sum()

print ("There are", duplicates, "duplicates in transactions.")

In [ ]:


    The transactions were recorded in anti-chronological order, i.e. the first rows contain the most recent transactions and the last rows the oldest transactions.

    (b) Eliminate duplicates from the database by keeping only the first occurrence, i.e. the most recent transaction.

    (c) Using the subset and keep parameters of the drop_duplicates method of transactions, display the most recent transaction for each category of prod_cat_code. To do this, you can remove all the duplicates from the prod_cat_code column by keeping only the first occurrence.



In [ ]:
transactions = transactions.drop_duplicates(keep = 'first')


transactions.drop_duplicates(subset = ['prod_cat_code'], keep = 'first')

### Modification of the elements of a DataFrame (replace, rename and astype methods)

In [ ]:
Modification of the elements of a DataFrame (replace, rename and astype methods)

    The replace method allows to replace one or more values ​​of a column of aDataFrame.

    Its header is as follows:

    replace(to_replace, value, ...)

            The to_replace parameter contains the value or the list of values to be replaced. It can be a list of integers, strings, booleans, etc.

            The value parameter contains the value or the list of the substitute values. It can also be a list of integers, strings, booleans, etc.



    In addition to modifying the elements of a DataFrame, it is possible to rename its columns.

    This is possible thanks to the rename method which takes as argument a dictionary whose keys are the old names and the values are the new names. You must also fill in the argument axis = 1 to specify that the names to rename are those of the columns.

    # Creation of the dictionary associating the old names with the new column names
    dictionary = {'old_name1': 'new_name1',
                  'old_name2': 'new_name2'}

    # We rename the variables using the rename method
    df = df.rename(dictionary, axis = 1)

    It is sometimes necessary to modify not only the name of a column but also its type.

    For example, it is possible that when importing a database, a variable is of type string when in fact it is a numerical variable. Whenever one of the entries in the column is incorrectly recognized, pandas will consider that this column is of type string.

    This is possible thanks to the astype method.

    The types that we will see most often are:

            str: Character string ('Hello').
            float: Floating point number (1.0, 1.14123).
            Int: Integer (1,1231)

    As for the rename method, astype can take as argument a dictionary whose keys are the names of the columns whose type should be modified and the values are the new types to assign. This is useful if you want to change the type of several columns at once.

    Most often, we will directly select the column whose type should be modified and overwrite it by applying the astype method to it.

    # Method 1: Creation of a dictionary then call to the astype method of the DataFrame
    dictionary = {'col_1': 'int',
                  'col_2': 'float'}
    df = df.astype(dictionary)

    # Method 2: Selection of the column and then calling the astype method of a Series
    df['col_1'] = df['col_1'].astype('int')

    These methods also have the inplace parameter to perform the operation directly on the DataFrame. To be used with great caution.

    If you make a mistake in the next exercise, you can re-import and redo the preprocessing by running the following cell.



In [ ]:
# Data import
transactions = pd.read_csv("transactions.csv", sep = ',', index_col = "transaction_id")

# Removal of duplicates
transactions = transactions.drop_duplicates(keep = 'first')

In [ ]:
    d) Import the numpy module under the namenp.

    (e) Replace the modalities ['e-Shop', 'TeleShop', 'MBR', 'Flagship store', np.nan] of the Store_type column by the modalities [1, 2, 3, 4, 0].

        The np.nan value is the one that encodes a missing value. We will replace this value with 0.

    (f) Convert the type of the columns Store_type and prod_subcat_code to type 'int'.

    (g) Rename the 'Store_type','Qty', 'Rate' and 'Tax' columns with 'store_type','qty', 'rate' and 'tax'.


In [ ]:
# Data import
transactions = pd.read_csv("transactions.csv", sep = ',', index_col = "transaction_id")

# Removal of duplicates
transactions = transactions.drop_duplicates(keep = 'first')

## Exercise

import numpy as np

# Replacement of values
transactions = transactions.replace(to_replace = ['e-Shop', 'TeleShop', 'MBR', 'Flagship store', np.nan],
                                    value = [1, 2, 3, 4, 0])

# Conversion of column types
new_types = {'Store_type'       : 'int',
             'prod_subcat_code' : 'int'}

transactions = transactions.astype(new_types)

# Renaming the columns
new_names = {'Store_type'   : 'store_type',
              'Qty'         : 'qty',
              'Rate'        : 'rate',
              'Tax'         : 'tax'}

transactions = transactions.rename(new_names, axis = 1)

# Display of the first rows of transactions
transactions.head()

### Operations on the values of a DataFrame (apply method and lambda functions)

In [ ]:
Operations on the values ​​of a DataFrame (apply method and lambda functions)

    It is often interesting to modify or aggregate the information of the columns of a DataFrame using an operation or a function.

    These operations can be any type of function which takes a column as argument. Thus, the numpy module is perfectly suited to perform operations on this type of object.

    The method used to perform an operation on a column is the apply method of a DataFrame whose header is:

    apply(func, axis, ...)

    where:

            func is the function to apply to the column.
            axis is the dimension on which the operation must be applied.

    Example: apply and np.sum

    For each column with numerical values, we want to calculate the sum of all rows. The sum function of numpy does this, so we can use it with the apply method.

    Since we are going to perform an operation on the rows, we must therefore specify the argument axis = 0 in the apply method.

    # Sum of the ROWS for each column of df
    df_lines = df.apply(np.sum, axis = 0)

    The result is the following:


    Now, for each row we want to compute the sum of all the columns.

    We are going to perform this operation on the columns, we must therefore specify the argument axis = 1 in the apply method.

    # Sum of columns for each ROW of df
    df_columns = df.apply(np.sum, axis = 1)

    The result is the following:

    These examples only illustrate the use of the apply method. To actually compute the sum of rows or columns, it is better to use the sum method of a DataFrame or a Series, which behaves in exactly the same way as the sum method of a numpy array.

The tran_date column of transactions contains the dates of the transactions in the format ('day-month-year') (ex: '28-02-2014'). The dates are of type string: it is not possible to perform statistics on this variable for the moment.

We would rather have 3 different columns for the day, month and year of each transaction. This would allow us, for example, to analyze and detect trends in transaction dates.

The date '28-02-2014' is a string. The day, month and year are separated by a hyphen '-'. The character string class has the split method to split a string on a specific character:

date = '28-02-2014 '

# Splitting the string on the '-' character
print(date.split('-'))
>>> ['28', '02', '2014']

This method returns a list containing the slices of the string on the specified character. Thus, to retrieve the day, all you have to do is select the first element of the split. To recover the month, we must take the second element and for the year the third.

    (h) Define a function get_day taking as argument a string and which returns the first element of its split by the character '-'.

    (i) Define the functions get_month and get_year which do the same with the second and third element of the split.

    (j) In 3 variables called days, months and years, store the result of the apply method on the tran_date column with the get_day, get_month and get_year functions. As these functions work element-wise, it is not necessary to specify the argument axis in the apply method.

    (k) Create the columns 'day', 'month' and 'year' in the transactions DataFrame and store the values of the days, months and years. Creating a new column is simply done by declaring it:

        # Create a new column 'day' with the values contained in days.
        transactions['day'] = days

    (l) Display the first 5 rows of transactions.



In [ ]:
# Definition of the functions to apply to the 'tran_date' column
def get_day(date):
    """
    Takes a date as a string argument.
    
    The date must have the format 'DD-MM-YYYY'.
    
    This function returns the day (DD).
    """
    
    # Splitting the string on the '-' character
    splits = date.split('-')
    
    # We return the first element of the breakdown (day)
    day = splits[0]
    return day

def get_month(date):
    return date.split('-')[1]

def get_year(date):
    return date.split('-')[2]
    
    
# Retrieving the day, month and year of each transaction
days = transactions['tran_date'].apply(get_day)
months = transactions['tran_date'].apply(get_month)
years = transactions['tran_date'].apply(get_year)

# Creation of new columns
transactions['day'] = days
transactions['month'] = months
transactions['year'] = years

# Displaying first rows of transactions
transactions.head()

In [ ]:


    The apply method is very powerful when combined with a lambda function.

    In Python, the keyword lambda is used to define an anonymous function: a function declared without name.

    A function lambda can take any number of arguments, but can only have one expression.

    Here is its syntax:

    lambda arguments: expression

    Lambda functions allow you to define functions with a very short syntax :

    # Example 1 
    x = lambda a: a + 2
    print(x(3))
    >>> 5

    # Example 2 
    x = lambda a, b : a * b
    print(x(2, 3))
    >>> 6

    # Example 3 
    x = lambda a, b, c : a - b + c
    print(x(1, 2, 3))
    >>> 2

    Although syntactically different, lambda functions behave in the same way as regular functions that are declared using the def keyword.

    The classic definition of a function is done with the def keyword:

    def increment(x):
        return x + 1

    It is also possible to define a function with the keyword lambda:

    increment = lambda x: x + 1

    The first method is very clean but the advantage of the second is that it can be defined on-the-fly directly within the apply method.

    Thus, the previous exercise can be done with a very compact syntax:

    transactions['day'] = transactions['tran_date'].apply(lambda date: date.split('-')[0])

    This kind of syntax is very practical and very often used for cleaning databases.

    The prod_subcat_code column of transactions depends on the prod_cat_code column because it identifies a subcategory of product. It would make more sense to have the category and subcategory of a product in the same variable.

    To do this, we will merge the values of these two columns:

            We will first convert the values of these two columns into strings using the astype method.

            Then, we will concatenate these strings to have a unique code representing both the category and sub-category. This can be done in the following way:

        string1 = "I think"
        string2 = "therefore I am."

        # Concatenation of the two strings by separating them with a space
        print (string1 + " " + string2)
        >>> I think therefore I am.

To apply a lambda function to an entire row, you must specify the argument axis = 1 in the apply method. In the function itself, the columns of the row can be accessed as on a DataFrame:

# Computation of the unit price of a product
transactions.apply(lambda row: row['total_ amt']/row['qty'], axis = 1)

    (m) Using a lambda function applied to transactions, create a column 'prod_cat' in transactions containing the concatenation of the values ofprod_cat_code and prod_subcat_code separated by a hyphen '-'. Remember to convert the values to strings.

    Displaying this column should yield:

    transaction_id
    80712190438     1-1
    29258453508     3-5
    51750724947     5-6
    93274880719     6-11
    51750724947     5-6
                   ...
    94340757522     5-12
    89780862956     1-4
    85115299378     6-2
    72870271171     5-11
    77960931771     5-11



In [ ]:
# Insert your code here
transactions['prod_cat'] = transactions.apply(lambda row : str(row['prod_cat_code']) + '-' + str(row['prod_subcat_code']),
                                    axis=1)
transactions.head()

# original cozum
transactions['prod_cat'] = transactions.astype('str').apply(lambda row: row['prod_cat_code']+'-'+row['prod_subcat_code'],
                                                            axis = 1)

print(transactions['prod_cat'])

## Dealing with missing values

In [ ]:
2. Dealing with missing values

    A missing value is either:

            An unspecified value.
            A value that does not exist. In general, they result from mathematical calculations having no solution (a division by zero for example).

    A missing value appears under the name NaN ("Not a Number") in a DataFrame.

    In this part, we will see several methods to:

            Detect missing values (isna and any methods)
            Replace these values (fillna method)
            Delete missing values (dropna method)

    In one of the previous exercises, we used the replace method of transactions to replace missing values with 0. This approach is not rigorous and should not be done in practice.

    For this reason, we are going to re-import the raw version of transactions to undo the steps we did in the previous exercises.

    (a) Run the cell below to re-import transactions, remove duplicates and rename its columns.



In [ ]:
# Data import
transactions = pd.read_csv("transactions.csv", sep = ',', index_col = "transaction_id")

# Duplicates removal
transactions = transactions.drop_duplicates(keep = 'first')

# Renaming the columns
new_names = {'Store_type'  : 'store_type',
              'Qty'        : 'qty',
              'Rate'       : 'rate',
              'Tax'        : 'tax'}

transactions = transactions.rename(new_names, axis = 1)

transactions.head()

### Detecting missing values (isna and any methods)

In [ ]:
Detecting missing values (isna and any methods)

    The isna method of a DataFrame detects its missing values. This method does not take any arguments.

    This method returns the same DataFrame whose values are:

            True if the original table cell is a missing value (np.nan)
            False otherwise.



    Since the isna method returns a DataFrame, we can use it with other methods of the DataFrame class to get more precise information:

            The any method - thanks to its axis argument - allows to determine which columns (axis = 0) or which rows (axis = 1) contain at least one missing value.

            The sum method counts the number of missing values per column or row (by specifying the axis argument). It is possible to use other statistical methods like mean,max, argmax, etc.

    Here are many examples of using the any and sum methods with isna:

    We use the DataFrame df from the previous illustrations:
    	Name 	Country 	Age
    0 	NaN 	Australia 	NaN
    1 	Duchamp 	France 	25
    2 	Hana 	Japan 	54

    The df.isna() instruction returns:
    	Name 	Country 	Age
    0 	True 	False 	True
    1 	False 	False 	False
    2 	False 	False 	False

    # COLUMNS containing at least one missing value are detected
    df.isna().any(axis = 0)

    >>> Name     True
    >>> Country  False
    >>> Age      True

    # ROWS containing at least one missing value are detected
    df.isna().any (axis = 1)

    >>> 0    True
    >>> 1    False
    >>> 2    False

    # Using conditional indexing to display entries
    # containing missing values
    df[df.isna().any(axis = 1)]

    which returns the DataFrame:
    	Name 	Country 	Age
    0 	NaN 	Australia 	NaN

    # We count the number of missing values for each COLUMN
    df.isnull().sum(axis = 0)

    >>> Name     1
    >>> Country  0
    >>> Age      1

    # Count the number of missing values for each ROW
    df.isnull().sum(axis = 1)

    >>> 0   2
    >>> 1   0
    >>> 2   0

    The methods isnaand isnullhave exactly the same behavior.

    (b) How many columns of the transactions DataFrame contain missing values?

    (c) How many of transactions' entries contain missing values? You can use the any method along with the sum method.

    (d) Which column of transactions contains the most of missing values? You can use the idxmax method that returns the index of first occurrence of maximum over the requested axis.

    (e) Show transaction entries that contain at least one missing value in the 'rate', 'tax' and 'total_amt' columns. What do you notice?



In [ ]:
# Which columns contain NaNs
columns_na = transactions.isna().any(axis = 0)

print(columns_na.sum(), "columns of transactions contain NaNs. \n")

# Which rows contain NaNs
rows_na = transactions.isna().any(axis = 1)

print(rows_na.sum(), "rows of transactions contain NaNs. \n")

# Number of NaNs per column
columns_nbna = transactions.isna().sum(axis = 0)

print ("The column containing the most NaNs is:",  columns_nbna.idxmax())

# Display the first 10 entries containing at least one NaN in 'rate', 'tax' or 'total_amt'
transactions[transactions[['rate', 'tax', 'total_amt']].isna().any(axis = 1)].head(10)

# The three variables are still missing together.

### Replacing missing values (fillna method)

In [ ]:
Replacing missing values (fillna method)

    The fillna method allows you to replace the missing values of a DataFrame by values you want.

    # We replace all the NaNs of the DataFrame by zeros
    df.fillna(0)

    # We replace the NaNs of each numerical column by the average on this column
    df.fillna(df.mean()) # df.mean() can be replaced by any statistical method.

    It is common to replace missing values of a column containing numerical values with statistics like:

            The mean: .mean
            The median: .median
            The minimum / maximum: .min / .max.

    For categorical type columns, replace the missing values with:

            The mode, i.e. the most frequent modality: .mode.
            A constant or arbitrary category: 0,-1.

    To avoid making replacement errors, it is very important to select the correct columns before using the fillna method.

If you make mistakes in the following exercise, you can re-import transactions using the following cell:


In [ ]:
# Data import
transactions = pd.read_csv("transactions.csv", sep = ',', index_col = "transaction_id")

# Removal of duplicates
transactions = transactions.drop_duplicates(keep = 'first')

# Renaming the columns
new_names = {'Store_type' : 'store_type',
              'Qty'       : 'qty',
              'Rate'      : 'rate',
              'Tax'       : 'tax'}

transactions = transactions.rename(new_names, axis = 1)

In [ ]:

    (f) Replace the missing values in prod_subcat_code column of transactions with -1.

    (g) Determine the most frequent modality (the mode) of the store_type column of transactions.

    (h) Replace the missing values of the store_type column by this modality. The value of this modality is accessed at index 0 of the Series returned by mode.

    (i) Check that the prod_subcat_code and store_type columns of transactions no longer contain missing values.



In [ ]:
# Replacing the NaNs of 'prod_subcat_code' by -1
transactions['prod_subcat_code'] = transactions['prod_subcat_code'].fillna(-1)

# Determining the mode of 'store_type'
store_type_mode = transactions['store_type'].mode()
print ("The most frequent mode of 'store_type' is:", store_type_mode[0])

# Replacing the NaNs of 'store_type' by its mode
transactions['store_type'] = transactions['store_type'].fillna(transactions['store_type'].mode()[0])

# Checking that these two columns no longer contain NANs
transactions[['prod_subcat_code', 'store_type']].isna().sum()

### Removing missing values (dropna method)

In [ ]:
Removing missing values (dropna method)

    The dropna method allows you to remove rows or columns containing missing values.

    The header of the method is as follows:

    dropna(axis, how, subset, ..)

            The axis parameter specifies whether to delete rows or columns (0 for rows, 1 for columns).

            The how parameter lets you specify how the rows (or columns) are deleted:

                    how = 'any': We delete the row (or column) if it contains at least one missing value.
                    how = 'all': We delete the row (or column) if it contains only missing values.

            The subset parameter is used to specify the columns/rows on which the search for missing values is carried out.

    Example:

    # We delete all the rows containing at least one missing value
    df = df.dropna(axis = 0, how = 'any')

    # We delete the empty columns
    df = df.dropna(axis = 1, how = 'all')

    # We remove the rows with missing values in the 3 columns 'col2', 'col3' and 'col4'
    df.dropna(axis = 0, how = 'all', subset = ['col2', 'col3', 'col4'])

    As with the other methods of replacing values of a DataFrame, the inplace argument can be used with great care to perform the modification directly without reassignment.

Transaction data for which the transaction amount is not provided is of no interest to us. For this reason:

    (j) Delete the transaction entries for which the rate, tax and total_amt columns are all empty.

    (k) Check that the columns of transactions no longer contain missing values.



In [ ]:
transactions = transactions.dropna(axis = 0, how = 'all', subset = ['rate', 'tax', 'total_amt'])

transactions.isna().sum(axis = 0)

## Conclusion and recap

In [ ]:
Conclusion and recap

    In this chapter we have seen the essential methods of the pandas module in order to clean up a dataset and manage missing values ​​(NaN).

    This step of preparing a dataset is always the first step of a data project.

    Regarding data cleaning, we have learned how to:

            Identify and delete duplicates of a DataFrame using the duplicated and drop_duplicates methods.

            Modify the elements of a DataFrame and their type using the replace, rename and astype methods.

            Apply a function to a DataFrame with the apply method and the lambda clause.

    Regarding the management of missing values, we have learned to:

            Detect them using the isna method followed by the any and sum methods.

            Replace them using the fillna method and the statistical methods.

            Delete them using the dropna method.

    In the following notebook, you will see other manipulations of DataFrames for a more advanced exploration of data.



## Apply, Lamda, Func Ornekleri (EXTRA)

In [85]:
import numpy as np

def get_day(string):
    day = string.split('-')[0]
    return day

def get_day_column(df, column):
    lst1 = [i.split('-')[0] for i in column]
    df['day2'] = np.array(lst1)
    return df['day2']
        
date1 = df.tran_date.iloc[0]
date1

print(get_day(date1))
# 1. Yol
df['day'] = df.tran_date.apply(get_day)

# 2. Yol
get_day_column(df, df.tran_date.values)

# 3. Yol 
df['day'] = df['tran_date'].apply(lambda x : x.split('-')[0])

# 4.yol
df[['day', 'month', 'year']] = df['tran_date'].str.split(expand=True)


28


transaction_id
80712190438    28
29258453508    27
51750724947    24
93274880719    24
51750724947    23
Name: day2, dtype: object

In [70]:
df.tran_date.values

array(['28-02-2014', '27-02-2014', '24-02-2014', '24-02-2014',
       '23-02-2014'], dtype=object)

In [83]:
df

cust_id   tran_date  prod_subcat_code  prod_cat_code  qty  \
transaction_id                                                              
80712190438      270351  28-02-2014                 1              1   -5   
29258453508      270384  27-02-2014                 5              3   -5   
51750724947      273420  24-02-2014                 6              5   -2   
93274880719      271509  24-02-2014                11              6   -3   
51750724947      273420  23-02-2014                 6              5   -2   

                  rate      tax  total_amt  store_type day month  year  \
transaction_id                                                           
80712190438     -772.0  405.300  -4265.300           1  28    02  2014   
29258453508    -1497.0  785.925  -8270.925           1  27    02  2014   
51750724947     -791.0  166.110  -1748.110           2  24    02  2014   
93274880719    -1363.0  429.345  -4518.345           1  24    02  2014   
51750724947     -791.0  166.110  -1748.110           2  23    02  2014   

                unit_price day2  
transaction_id                   
80712190438        853.060   28  
29258453508       1654.185   27  
51750724947        874.055   24  
93274880719       1506.115   24  
51750724947        874.055   23

In [38]:
import pandas as pd
#df_names = pd.read_clipboard()
df_names

Name         Car
0      Lila      Twingo
1     Tiago        Clio
2  Berenice   C4 Cactus
3    Joseph      Twingo
4     Kader       Swift
5      Romy      Scenic

In [37]:
#df_cars = pd.read_clipboard()
df_cars

Car  Price
0     Twingo   11000
1      Swift   14500
2  C4 Cactus   23000
3       Clio   16000
4      Prius   30000

In [59]:
df120158 = pd.read_clipboard()
df120158

symboling  normalized-losses  wheel-base  length  width  height  \
120          0                 91        95.7   166.3   64.4    52.8   
121          0                 91        95.7   166.3   64.4    52.8   
122          1                168        94.5   168.7   64.0    52.6   
123          1                168        94.5   168.7   64.0    52.6   
124          1                168        94.5   168.7   64.0    52.6   
125          1                168        94.5   168.7   64.0    52.6   
126          2                134        98.4   176.2   65.6    52.0   
127          2                134        98.4   176.2   65.6    52.0   
128          2                134        98.4   176.2   65.6    52.0   
129          2                134        98.4   176.2   65.6    52.0   
130          2                134        98.4   176.2   65.6    52.0   
131          2                134        98.4   176.2   65.6    53.0   
132         -1                 65       102.4   175.6   66.5    54.9   
133         -1                 65       102.4   175.6   66.5    54.9   
134         -1                 65       102.4   175.6   66.5    53.9   
135         -1                 65       102.4   175.6   66.5    54.9   
136         -1                 65       102.4   175.6   66.5    53.9   
137          3                197       102.9   183.5   67.7    52.0   
138          3                197       102.9   183.5   67.7    52.0   
139         -1                 90       104.5   187.8   66.5    54.1   
140          2                122        97.3   171.7   65.5    55.7   
141          2                122        97.3   171.7   65.5    55.7   
142          2                 94        97.3   171.7   65.5    55.7   
143          2                 94        97.3   171.7   65.5    55.7   
144          2                 94        97.3   171.7   65.5    55.7   
145          2                 94        97.3   171.7   65.5    55.7   
146          2                 94        97.3   171.7   65.5    55.7   
147          3                256        94.5   165.7   64.0    51.4   
148         -2                103       104.3   188.8   67.2    56.2   
149         -1                 74       104.3   188.8   67.2    57.5   
150         -2                103       104.3   188.8   67.2    56.2   
151         -1                 74       104.3   188.8   67.2    57.5   
152         -2                103       104.3   188.8   67.2    56.2   
153         -1                 74       104.3   188.8   67.2    57.5   
154         -1                 95       109.1   188.8   68.9    55.5   
155         -1                 95       109.1   188.8   68.8    55.5   
156         -1                 95       109.1   188.8   68.9    55.5   
157         -1                 95       109.1   188.8   68.9    55.5   
158         -1                 95       109.1   188.8   68.9    55.5   

     curb-weight  engine-size  bore  stroke  compression-ratio  horsepower  \
120         2122           98  3.19    3.03                9.0          70   
121         2140           98  3.19    3.03                9.0          70   
122         2169           98  3.19    3.03                9.0          70   
123         2204           98  3.19    3.03                9.0          70   
124         2265           98  3.24    3.08                9.4         112   
125         2300           98  3.24    3.08                9.4         112   
126         2540          146  3.62    3.50                9.3         116   
127         2536          146  3.62    3.50                9.3         116   
128         2551          146  3.62    3.50                9.3         116   
129         2679          146  3.62    3.50                9.3         116   
130         2714          146  3.62    3.50                9.3         116   
131         2975          146  3.62    3.50                9.3         116   
132         2326          122  3.31    3.54                8.7          92   
133         2480          110  3

In [66]:
df_auto = pd.concat([df60, df60120, df120158])
df_auto

symboling  normalized-losses  wheel-base  length  width  height  \
0            2                164        99.8   176.6   66.2    54.3   
1            2                164        99.4   176.6   66.4    54.3   
2            1                158       105.8   192.7   71.4    55.7   
3            1                158       105.8   192.7   71.4    55.9   
4            2                192       101.2   176.8   64.8    54.3   
..         ...                ...         ...     ...    ...     ...   
154         -1                 95       109.1   188.8   68.9    55.5   
155         -1                 95       109.1   188.8   68.8    55.5   
156         -1                 95       109.1   188.8   68.9    55.5   
157         -1                 95       109.1   188.8   68.9    55.5   
158         -1                 95       109.1   188.8   68.9    55.5   

     curb-weight  engine-size  bore  stroke  compression-ratio  horsepower  \
0           2337          109  3.19    3.40               10.0         102   
1           2824          136  3.19    3.40                8.0         115   
2           2844          136  3.19    3.40                8.5         110   
3           3086          131  3.13    3.40                8.3         140   
4           2395          108  3.50    2.80                8.8         101   
..           ...          ...   ...     ...                ...         ...   
154         2952          141  3.78    3.15                9.5         114   
155         3049          141  3.78    3.15                8.7         160   
156         3012          173  3.58    2.87                8.8         134   
157         3217          145  3.01    3.40               23.0         106   
158         3062          141  3.78    3.15                9.5         114   

     peak-rpm  city-mpg  highway-mpg  price  
0        5500        24           30  13950  
1        5500        18           22  17450  
2        5500        19           25  17710  
3        5500        17           20  23875  
4        5800        23           29  16430  
..        ...       ...          ...    ...  
154      5400        23           28  16845  
155      5300        19           25  19045  
156      5500        18           23  21485  
157      4800        26           27  22470  
158      5400        19           25  22625  

[159 rows x 16 columns]

In [67]:
df_auto.to_csv('automobiles.csv')

symboling  normalized-losses  wheel-base      length       width  \
count  159.000000         159.000000  159.000000  159.000000  159.000000   
mean     0.735849         121.132075   98.264151  172.413836   65.607547   
std      1.193086          35.651285    5.167416   11.523177    1.947883   
min     -2.000000          65.000000   86.600000  141.100000   60.300000   
25%      0.000000          94.000000   94.500000  165.650000   64.000000   
50%      1.000000         113.000000   96.900000  172.400000   65.400000   
75%      2.000000         148.000000  100.800000  177.800000   66.500000   
max      3.000000         256.000000  115.600000  202.600000   71.700000   

           height  curb-weight  engine-size        bore      stroke  \
count  159.000000   159.000000   159.000000  159.000000  159.000000   
mean    53.899371  2461.138365   119.226415    3.300126    3.236352   
std      2.268761   481.941321    30.460791    0.267336    0.294888   
min     49.400000  1488.000000    61.000000    2.540000    2.070000   
25%     52.250000  2065.500000    97.000000    3.050000    3.105000   
50%     54.100000  2340.000000   110.000000    3.270000    3.270000   
75%     55.500000  2809.500000   135.000000    3.560000    3.410000   
max     59.800000  4066.000000   258.000000    3.940000    4.170000   

       compression-ratio  horsepower     peak-rpm    city-mpg  highway-mpg  \
count         159.000000  159.000000   159.000000  159.000000   159.000000   
mean           10.161132   95.836478  5113.836478   26.522013    32.081761   
std             3.889475   30.718583   465.754864    6.097142     6.459189   
min             7.000000   48.000000  4150.000000   15.000000    18.000000   
25%             8.700000   69.000000  4800.000000   23.000000    28.000000   
50%             9.000000   88.000000  5200.000000   26.000000    32.000000   
75%             9.400000  114.000000  5500.000000   31.000000    37.000000   
max            23.000000  200.000000  6600.000000   49.000000    54.000000   

              price  
count    159.000000  
mean   11445.729560  
std     5877.856195  
min     5118.000000  
25%     7372.000000  
50%     9233.000000  
75%    14719.500000  
max    35056.000000

# Extra Filtering

In [ ]:
listem = ['y', 'n'] # İstenen veri listesi
count = 0 # Sayacı sıfırla
for col in df.iloc[:, 1:].columns: # Sütunları döngüye sok
    for val in df[col].values: # Her bir hücreyi döngüye sok
        if val not in listem: # Eğer hücrenin değeri listede yoksa
            count += 1 # Sayacı arttır
count


count = sum([sum([1 for val in col if val not in ['y', 'n']]) for col in df.values])
count


check = all(all(val in ['y', 'n'] for val in col) for col in df.values)
check


df.apply(lambda x : x.isin(['y', 'n']) == False) # bitmedi daha???