 NumPy for Data Science
Operations on Numpy arrays

# Operations on Numpy arrays

## Arithmetic operators

In [ ]:
1. Arithmetic operators

    Numpy allows you to perform mathematical operations on arrays in an optimized way.

            Applying one of the basic arithmetic operations (/, *, -,+,**) between an array and a value will apply the operation to each of the elements of the array.

            It is also possible to perform an arithmetic operation between two arrays. This will apply the operation between each pair of elements.

        # Creation of two arrays with 2 values
        a = np.array([4, 10])
        b = np.array([6, 7])

        # Multiplication between two arrays
        print(a * b)
        >>> [24, 70]

    (a) Import the package numpy under the name np.

    (b) Create an array of dimensions 10x4 filled with ones.

    (c) Using a for loop and the enumerate function, multiply each row by its index. In order to modify the matrix,
    it must be accessed through indexing.


In [22]:
import numpy as np

X = np.ones((3,2))

for n, arr in enumerate(X):
    print(n, arr)

0 [1. 1.]
1 [1. 1.]
2 [1. 1.]


In [23]:
# If the array of the value is bigger than 1 then compute 2 powers of value 
X = np.ones((10,4))
X = X * [i for i in range(4)]
print(X[:2])

for i, row in enumerate(X):
    for j in row:
        if j > 1:
            X[i,int(j)] **= 2
            
X

[[0. 1. 2. 3.]
 [0. 1. 2. 3.]]


array([[0., 1., 4., 9.],
       [0., 1., 4., 9.],
       [0., 1., 4., 9.],
       [0., 1., 4., 9.],
       [0., 1., 4., 9.],
       [0., 1., 4., 9.],
       [0., 1., 4., 9.],
       [0., 1., 4., 9.],
       [0., 1., 4., 9.],
       [0., 1., 4., 9.]])

In [24]:
# Insert your code here
import numpy as np

X = np.ones((10,4))

for n, arr in enumerate(X):
    print(n * arr)

[0. 0. 0. 0.]
[1. 1. 1. 1.]
[2. 2. 2. 2.]
[3. 3. 3. 3.]
[4. 4. 4. 4.]
[5. 5. 5. 5.]
[6. 6. 6. 6.]
[7. 7. 7. 7.]
[8. 8. 8. 8.]
[9. 9. 9. 9.]


In [25]:
#original cozum 
import numpy as np

M = np.ones((10, 4))

# For each row of the matrix M
for i, row in enumerate(M):
    # We multiply the row by its index
    M[i,:] = row*i
    # Alternatively M[i,:]* = i
    
print(M)

[[0. 0. 0. 0.]
 [1. 1. 1. 1.]
 [2. 2. 2. 2.]
 [3. 3. 3. 3.]
 [4. 4. 4. 4.]
 [5. 5. 5. 5.]
 [6. 6. 6. 6.]
 [7. 7. 7. 7.]
 [8. 8. 8. 8.]
 [9. 9. 9. 9.]]


In [ ]:
As explained above, the * operator allows you to compute an element-wise product between arrays.

For example:

(5310)∗(2048)=(10040)

The matrix product, in the mathematical sense of the term, can be performed using the dot method of a numpy array:

# Creation of two arrays of size 2x2
M = np.array([[5, 1],
              [3, 0]])

N = np.array([[2, 4],
              [0, 8]])

# Matrix product between the two arrays
print(M.dot(N))
>>> [[10, 28]
>>>  [6, 12]]

Indeed, if we recall the matrix product:

𝑀=([5, 1],
    [3, 0]),
𝑁=([2, 4],
    [0, 8])

𝑀𝑁=(5310)(2048)=((5∗2)+(1∗0)(3∗2)+(0∗0)(5∗4)+(1∗8)(3∗4)+(0∗8))=[[10, 28],
                                                                 [ 6, 12]])
Let's consider the following matrix:

𝐴=(1−1−11)

    (d) Define a function named powerA taking as argument an integer n greater than 1. This function must compute and return 𝐴^𝑛

    (according to matrix product).

    (e) Calculate and display 𝐴^2, 𝐴^3 and 𝐴^4. Can you guess a general formula for 𝐴^𝑛?

In [26]:
M = np.array([[5, 1],
              [3, 0]])


N = np.array([[2, 4],
              [0, 8]])



def powerA(n, A, B):

    for i in range(n):
        at = A @ B
        A = A.dot(B)
    return A, at         


powerA(1, M, N)

(array([[10, 28],
        [ 6, 12]]),
 array([[10, 28],
        [ 6, 12]]))

In [27]:
# original cozum
def powerA(n):
    # A is initialized to the identity matrix
    A = np.array([[1, 0],
                  [0, 1]])
    
    # This matrix B will be used to calculate the powers of A
    B = np.array([[1, -1],
                  [-1, 1]])
    
    # We multiply A by B n times to get A**n
    for i in range(n):
        A = A.dot(B)
        
    return A

print ("A**2: \n", powerA(2), "\n")
print ("A**3: \n", powerA(3), "\n")
print ("A**4: \n", powerA(4), "\n")

print ("A general formula of A**n is given by:")
print ("[2**(n-1), -2**(n-1)]")
print ("[-2**(n-1), 2**(n-1)]")

A**2: 
 [[ 2 -2]
 [-2  2]] 

A**3: 
 [[ 4 -4]
 [-4  4]] 

A**4: 
 [[ 8 -8]
 [-8  8]] 

A general formula of A**n is given by:
[2**(n-1), -2**(n-1)]
[-2**(n-1), 2**(n-1)]


In [ ]:
In a two-dimensional plane, rotations around the origin are represented by the matrices of the form:

𝐴(𝜃)=(cos(𝜃) −sin(𝜃)
     sin(𝜃)  cos(𝜃))
where 𝜃 defines the angle of the rotation in radians. Thus, the rotation of a point with coordinates 𝑥=(𝑥1𝑥2) is calculated thanks to the formula 𝑥̃ =𝐴(𝜃)𝑥

    (f) Define a function named rotation_matrix taking as argument a number 𝜃

(theta) and returning the associated 𝐴(𝜃) matrix. You can calculate the cos and sin

    functions using the np.cos andnp.sin functions of numpy.

    (g) Let 𝑥=(1
                1)

be a point. Calculate and display 𝐴(𝜋)𝑥, which is equivalent to rotating 180º around the origin. You have access to the constant 𝜋

    with the np.pi instruction.

    (h) Show that 𝐴(𝜋4)𝐴(3𝜋4)𝑥=𝐴(𝜋)𝑥

    .

    (i) Generally speaking, for any angle, 𝐴(𝜃1)𝐴(𝜃2)𝑥=𝐴(𝜃1+𝜃2)𝑥

. Why is this the case?

In [30]:
# Insert your code here

def rotation_matrix(theta, X):
    Y = np.array([[np.cos(theta), -np.sin(theta)],
                  [np.sin(theta), np.cos(theta)]])
    return Y.dot(X)

#g)
x = np.array([1,1])

x_pi = rotation_matrix(np.pi, x)

print(x, x_pi )

#h)
a_pi_4 = rotation_matrix(np.pi/4, x)
a_3pi_4 = rotation_matrix(3*np.pi/4, x)

print(a_pi_4.dot(a_3pi_4), x_pi)

[1 1] [-1. -1.]
0.0 [-1. -1.]


In [31]:
# Insert your code here

def rotation_matrix(theta):
    Y = np.array([[np.cos(theta), -np.sin(theta)],
                  [np.sin(theta), np.cos(theta)]])
    return Y

#g)
x = np.array([1,1])

x_pi = rotation_matrix(np.pi)

print(x, x_pi.dot(x))

#h)
x = np.array([1,1])
a_pi_4 = rotation_matrix(np.pi/4)
a_3pi_4 = rotation_matrix(3*np.pi/4)

print(x, a_pi_4.dot(a_3pi_4.dot(x)), "\n")

#i)
pi = 100*np.pi
pi_2 = 200*np.pi

a_theta1 = rotation_matrix(pi)
a_theta2 = rotation_matrix(pi_2)
a_sum = rotation_matrix(pi + pi_2)

print("a_theta1 \n\n",a_theta1, "\n a_theta2 \n\n", a_theta2, "\n a_sum \n\n", a_sum, "\n")
print(a_theta1.dot(a_theta2.dot(x)))
print(a_sum.dot(x))

[1 1] [-1. -1.]
[1 1] [-1. -1.] 

a_theta1 

 [[ 1.00000000e+00 -1.96438672e-15]
 [ 1.96438672e-15  1.00000000e+00]] 
 a_theta2 

 [[ 1.00000000e+00 -3.92877345e-15]
 [ 3.92877345e-15  1.00000000e+00]] 
 a_sum 

 [[ 1.00000000e+00  5.09502587e-14]
 [-5.09502587e-14  1.00000000e+00]] 

[1. 1.]
[1. 1.]


In [29]:
#original cozum
#????????

# First question
def rotation_matrix(theta):
    A = np.array([[np.cos(theta), -np.sin(theta)],
                  [np.sin(theta), np.cos(theta)]])
    
    return A

# Second question
x = np.array([1, 1])
A_pi = rotation_matrix(np.pi)

print("x =", x)
print("A(pi)x =", A_pi.dot(x))

# Third question
A_pi_4 = rotation_matrix(np.pi/4)
A_3pi_4 = rotation_matrix(3*np.pi/4)

print("A(pi/4) A(3pi/4) x =", A_pi_4.dot(A_3pi_4.dot(x)))

# Fourth question
print("\n")
print("Intuitively, A(theta_1) A(theta_2) = A(theta_1 + theta_2) because applying a rotation of angle theta_1 then" )
print("applying another rotation of angle theta_2 is exactly the same as applying a rotation whose angle is the sum of the two.")

x = [1 1]
A(pi)x = [-1. -1.]
A(pi/4) A(3pi/4) x = [-1. -1.]


Intuitively, A(theta_1) A(theta_2) = A(theta_1 + theta_2) because applying a rotation of angle theta_1 then
applying another rotation of angle theta_2 is exactly the same as applying a rotation whose angle is the sum of the two.


## Broadcasting between a matrix and a value

In [ ]:
2. Broadcasting between a matrix and a value

    When performing an operation between elements of different dimensions, Numpy performs what is called Broadcasting to understand the operation and execute it.

    The term broadcasting is used because one of the arrays is "broadcasted" into an array of larger dimensions so that the two arrays have compatible dimensions. This definition will be illustrated below.

    In this section, we will try to understand numpy's broadcasting rules in the following cases:

        Operation between a matrix and a constant
        Operation between a matrix and a vector

    An arithmetic operation such as the sum between a matrix and a constant does not make mathematical sense. With Numpy, the broadcasting rule in this case is to sum the constant to each term of the matrix.

    𝑀=(3−21125),𝑐=10

𝑀+𝑐=(3+10−2+101+101+102+105+10)=(13811111215)

What really happens is that the constant 𝑐
is broadcasted into a matrix 𝐶 with the same dimensions as 𝑀

:

𝑐⟶broadcasting𝐶=(𝑐𝑐𝑐𝑐𝑐𝑐)

Thus, 𝑀+𝐶

    is mathematically well defined and can be computed with basic operations.



## Broadcasting between a matrix and a vector

In [1]:
3. Broadcasting between a matrix and a vector

    Similarly, numpy allows us to perform arithmetic operations between a matrix and a vector. However, there are some constraints which determine whether the vector can be broadcasted into a matrix with compatible dimensions.

    In order to determine if the dimensions of the vector and the matrix are compatible, numpy will compare each dimension of the two arrays and determine if:

        the dimensions are equal.
        one of the dimensions is equal to 1.

    If for each dimension, one of these conditions is verified, then the dimensions are compatible and the operation has been understood. Otherwise, a ValueError: operands could not be broadcast together error will be displayed.

    Let us consider the following objects :

    𝑀=(3−21125),𝑣=(25)

Do 𝑀
and 𝑣

have compatible dimensions for broadcasting?

𝑀
is a 2x3 dimensional matrix. 𝑣 is a vector with 2 elements, but numpy will instead see 𝑣

as a matrix of dimensions 2x1, that is, a matrix with two rows and one column.

The first dimension of 𝑀
and 𝑣 is equal to 2

. They are equal so the compatibility condition is verified for this dimension.

The second dimension of 𝑀
is equal to 3 and that of 𝑣

is equal to 1. The compatibility condition is still verified because one of the dimensions is equal to 1.

Therefore 𝑀
and 𝑣

have compatible dimensions for broadcasting.

The vector 𝑣
will then be broadcasted along the axis where the dimension of 𝑣 is equal to 1. In our case, it is the axis of the columns. The broadcasting of 𝑣

will therefore be given by:

𝑣=(25)⟶broadcasting𝑉=[𝑣𝑣𝑣]=(252525)

The result of 𝑀∗𝑣

will then be given by:

𝑀∗𝑣⟶broadcasting𝑀∗𝑉=(3∗2−2∗51∗21∗52∗25∗5)=(6−1025425)

Now suppose we have a line vector 𝑢=(34)

.

For numpy, this vector has dimensions 1x2 (one row and 2 columns). The vectors 𝑢
and 𝑣

are compatible for broadcasting because on each axis one of the vectors has a dimension equal to 1.

How and on which object is the broadcasting carried out in this case?

The broadcasting will be carried out on the two vectors and the resulting matrix of the broadcasting will have the largest dimension between the two vectors:

𝑣=(25)⟶broadcasting𝑉=(2525)

and

𝑢=(34)⟶broadcasting𝑈=(3344)

Thus, the result of 𝑣+𝑢

is given by:

𝑣+𝑢⟶broadcasting=(25)+(34)𝑉+𝑈=(2525)+(3344)=(5869)

    These rules allow us to understand and predict the result of an operation between two arrays which do not have the same shape. They will be useful for the following exercise:

    Min-Max normalization is a method that is used to rescale the variables of a database to the interval [0,1]

.

Assume our database contains 3 individuals and 2 variables:

        Jacques: 24 years old, height of 1.88m.

        Mathilde: 18 years old, height of 1.68m.

        Alban: 14 years old, height of 1.65m.

This data can be represented by the matrix:

𝑋=2418141.881.681.65

Each row corresponds to an individual, and each column corresponds to a variable. This format is the standard format for databases.

We want to compare the age differences with the height differences between individuals. However, the variables in this database do not have the same scale. We have to use Min-Max normalization so that the variables have the same scale.

We denote by 𝑋𝑖,𝑗
the value of the variable 𝑗 for the individual 𝑖 and 𝑋:,𝑗 the column of the variable 𝑗

.

Min-Max normalization will produce a new matrix 𝑋̃ 
such that for each entry of the 𝑋

matrix:

𝑋̃ 𝑖,𝑗=𝑋𝑖,𝑗−min(𝑋:,𝑗)max(𝑋:,𝑗)−min(𝑋:,𝑗)

Thus, to implement Min-Max normalization :

        For each 𝑋:,𝑗

column, compute min(𝑋:,𝑗) and max(𝑋:,𝑗)

    .

    For each element 𝑋𝑖,𝑗

in the column, compute 𝑋̃ 𝑖,𝑗

        .

By default, a for loop on 𝑋 will cycle through the lines of 𝑋. 
In order to browse the columns of 𝑋, you can browse the rows of the transposed matrix of 𝑋, which we denote by 𝑋𝑇

.

𝑋𝑇=(241.88181.68141.65)

The transposition of an array is obtained with its T attribute: 𝑋𝑇

    =X.T.

    (a) Define a function named normalization_min_max taking as argument a matrix 𝑋 and which will return 𝑋̃ 

    (b) Apply Min-Max normalization on 𝑋 . You should get the matrix to two decimal places:

X = np.array([[1, 0.4, 0],
              [1, 0.13, 0]])

In [32]:
# Insert your code here

def normalization_min_max(X):
    if X.ndim == 1:
        l2 = []
        for i in X:
            new_i = (i - min(X)) / (max(X) - min(X))
            l2.append(round(new_i, 2))
        return l2
    else:
        X = X.T
        for i, row in enumerate(X):
            mi = min(row)
            ma = max(row)
            for j, value in enumerate(row):
                new_value = (value - mi) / (ma - mi)
                X[i,j] = round(new_value, 2)

        return X.T

l = np.array([1,2,3,4])

X = np.array([[1, 0.4, 0],
              [1, 0.13, 0]])

y = np.array([[24, 1.88],
              [18, 1.68],
              [14, 1.65]])
normalization_min_max(l)
normalization_min_max(y)
#normalization_min_max(X) 

array([[1.  , 1.  ],
       [0.4 , 0.13],
       [0.  , 0.  ]])

In [33]:
# original cozum
def normalization_min_max(X):
    # Initialization of X_tilde
    X_tilde = np.zeros(shape = X.shape)
    
    # For each column of X
    for j, column in enumerate(X.T):
        # Initialization of the minimum and maximum of the column
        min_Xj = column[0]
        max_Xj = column[0]
        
        # For each value in the column
        for value in column:
            # If the value is SMALLER than the min
            if value < min_Xj:
                # We overwrite the min with this value
                min_Xj = value
            
            # If the value is GREATER than the max
            if value > max_Xj:
                # We overwrite the max with this value
                max_Xj = value
                
        # We can now calculate X_tilde for this column
        # Broadcasting allows us to do this without a for loop
        X_tilde[:, j] = (X[:, j] - min_Xj)/(max_Xj - min_Xj)
            
    return X_tilde
        

X = np.array([[24, 1.88],
              [18, 1.68],
              [14, 1.65]])

X_tilde = normalization_min_max(X)

print(X_tilde)

[[1.         1.        ]
 [0.4        0.13043478]
 [0.         0.        ]]


## Statistical methods

In [ ]:
4. Statistical methods

    In addition to common math operations, numpy arrays also have several methods for more complex operations on arrays.

    One of the most used operations is the computation of an average using the mean method of an array:

    A = np.array([[1, 1, 10],
                  [3, 5, 2]])

    # Computation of the mean over ALL the values of X
    print(A.mean())
    >>> 3.67

    # Computation of the mean of each COLUMN of X
    print(A.mean(axis = 0))
    >>> [2, 3, 6]

    # Computation of the mean of each ROW of X
    print(A.mean(axis = 1))
    >>> [4, 3.33]

    The argument axis determines which dimension will be scanned to compute the mean:

            axis = 0 means that the dimension scanned will be that of rows, which means that the result will be the average of each column.

            axis = 1 means that the dimension scanned will be that of columns, which means that the result will be the average of each row.

    The axis argument is very often used for operations on matrices, and not only for Numpy. It is very important to understand its effect.

    There are other statistical methods that behave like the mean method, such as:

            sum: Computes the sum of the elements of an array.

            std: Computes the standard deviation.

            min: Finds the minimum value among the elements of an array.

            max: Finds the maximum value among the elements of an array.

            argmin: Returns the index of the minimum value.

            argmax: Returns the index of the maximum value.

    These methods are useless for databases if you do not provide a value for the axis argument.

    In general, we will use the value axis = 0 to get the result for each column, that is, for each variable in the database.

    Thus, we can calculate the Min-Max normalization very quickly using the min and max methods along with broadcasting:

    X_tilde = (X - X.min(axis = 0))/(X.max(axis = 0) - X.min(axis = 0))

    print (X_tilde)
    >>> [[1, 1]
    >>>  [0.4, 0.13043478]
    >>>  [0, 0]]

The Mean Squared Error is a metric to quantify the prediction error obtained by a regression model. This notion will be seen in more detail later in your training.

The formula for the mean squared error, abbreviated by MSE

, is calculated with the following formula:

MSE=1𝑛∑𝑖=1𝑛(𝑦̂ 𝑖−𝑦𝑖)2

where:

        𝑦̂ 

and 𝑦 are vectors with length 𝑛

    .

    𝑦̂ 

is given by the matrix product between a 𝑋 matrix and a regression vector 𝛽, ie:
𝑦̂ =𝑋𝛽

In the case of linear regression, the goal of the mean squared error is to find the regression vector 𝛽

which minimizes this error.

    (a) Define a function named mean_squared_error taking as argument a matrix X
    , a vector beta and a vector y and which, without a for loop, returns the associated mean squared error.


In [34]:
# original cozum
def mean_squared_error(X, beta, y):
    # Computation of ^y
    y_hat = X.dot(beta)
    
    # Computation of (^y_i - y_i)**2
    mse = (y_hat - y)**2
    
    # MSE
    mse = mse.mean()
    
    return mse

In [ ]:
Our database contained 3 individuals and 2 variables:

        Jacques: 24 years old, height 1.88m.

        Mathilde: 18 years old, height 1.68m.

        Alban: 14 years old, height 1.65m.

We will try to find a model able to predict the height of an individual based on his age. Thus, we define:
𝑋=241814

𝑦=1.881.681.65

Our goal will be to find an optimal 𝛽∗
such that:
𝑦≈𝑋𝛽∗

    (b) For beta taking the values 0.01, 0.02, ..., 0.13, 0.14 and 0.15, compute the associated MSE

    using the previously defined mean_squared_error function. Store the values in a list.

    To create the list [0.01, 0.02, ..., 0.13, 0.14, 0.15], you can use the np.linspace function which has a signature similar to the range function:

    print(np.linspace(start = 0.01, stop = 0.15, num = 15))
    >>> [0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1, 0.11, 0.12, 0.13, 0.14, 0.15]

    The num argument allows you to define the desired number of elements between start and stop. It is not the step between two consecutive values.


In [35]:
X = np.array([24,
              18,
              14])

y = np.array([1.88,
              1.68,
              1.65])

# Insert your code here


lst = np.linspace(0.01, 0.15, 15)
result = []
for beta in  lst:
    result.append([mean_squared_error(X, beta, y), beta])

#print(result)
print("Mininmun MSE and Optimal Beta :",min(result))

Mininmun MSE and Optimal Beta : [0.07803333333333334, 0.08999999999999998]


In [36]:
# original cozum
X = np.array([24,
              18,
              14])

y = np.array([1.88,
              1.68,
              1.65])

# List containing the mse
errors = []

# List containing the betas to be tested
betas = np.linspace(start = 0.01, stop = 0.15, num = 15)

# For all the values of beta
for beta in betas:
    # Compute the associated MSE
    errors.append(mean_squared_error(X, beta, y))

In [ ]:
(c) Convert the list containing the MSE

    's to a numpy array.

    (d) Determine the 𝛽∗

that minimizes the MSE using the argmin method.

In [37]:
# Insert your code here

errs_arr = np.array(errors)
print("Array of MSE : \n", errs_arr, "\n")

min_err_index = errs_arr.argmin()
print("Min MSE index :", min_err_index, "\n")

print("Minimum MSE = ",errs_arr[min_err_index], "\n")
print("Optimal Beta = ", betas[min_err_index])

Array of MSE : 
 [2.40656667 1.85976667 1.38603333 0.98536667 0.65776667 0.40323333
 0.22176667 0.11336667 0.07803333 0.11576667 0.22656667 0.41043333
 0.66736667 0.99736667 1.40043333] 

Min MSE index : 8 

Minimum MSE =  0.07803333333333334 

Optimal Beta =  0.08999999999999998


In [38]:
# original cozum
# Array containing the MSE for each beta
errors = np.array(errors)

# List containing the betas that have been tested
betas = np.linspace(start = 0.01, stop = 0.15, num = 15)

# Index of the beta that minimizes the MSE 
index_beta_optimal = errors.argmin()

# Optimal beta 
beta_optimal = betas[index_beta_optimal]

print("The optimal beta is:", beta_optimal)

The optimal beta is: 0.08999999999999998


In [ ]:
e) What are the heights predicted by this optimal 𝛽∗? The heights predicted by the model are given by the vector 𝑦̂ =𝑋𝛽∗

    .

(f) Compare the predicted heights to the actual heights of the individuals. 
For example, you can compute the average absolute difference between the predicted and true values using the absolute value (np.abs).


In [39]:
# Insert your code here

y_predict = X.dot(beta_optimal)
print("Predicted heights : ",y_predict)


print("Real heights      : ", y)

errors_ = np.abs(y - y_predict)

print("Erros             : ", errors_)

print("Average of errors : ", errors_.mean())


Predicted heights :  [2.16 1.62 1.26]
Real heights      :  [1.88 1.68 1.65]
Erros             :  [0.28 0.06 0.39]
Average of errors :  0.2433333333333334


In [40]:
y_hat = X.dot(beta_optimal)
print("Predicted heights: \n", y_hat)

print("\n Real heights: \n", y)

print("\n The model makes an average mistake of", np.abs(y - y_hat).mean(), "metres.")

# The predicted heights are incorrect but approximately very close to the real sizes.

Predicted heights: 
 [2.16 1.62 1.26]

 Real heights: 
 [1.88 1.68 1.65]

 The model makes an average mistake of 0.2433333333333334 metres.


# Introduction to DataFrames 

In [ ]:
Introduction

    The pandas module has been developed to provide Python with the tools necessary to manipulate and analyze large volumes of data.

    Pandas introduces the DataFrame class, an array-like data structure that offers more advanced data manipulation and exploration than NumPy arrays.

    The main features of pandas are:

            data recovery from files (CSV, Excel tables, etc.)

            handling this data (deletion / addition, modification, statistical visualization, etc.).

    This notebook aims at:

            Understanding the format of a DataFrame.

            Creating a first Dataframe.

            Carrying out a first exploration of a dataset using the DataFrame class.

    (a) Import the pandas module under the name pd.


In [ ]:
# Insert your code here
import pandas as pd

## Format of a DataFrame

In [ ]:
1. Format of a DataFrame

    A DataFrame is in the form of a matrix whose rows and columns each have an index. Typically, columns are indexed by name and rows by unique identifiers.

    A DataFrame is used to store a database. The different entries in the database (individuals, animals, objects, etc.) are the different lines and their features are the different columns:
    	Name 	Gender 	Height 	Age
    0 	Robert 	M 	174 	23
    1 	Mark 	M 	182 	40
    2 	Aline 	F 	169 	56

            The DataFrame above groups together information on 3 individuals: the DataFrame therefore has 3 lines.

            For each of these individuals, there are 4 variables (name, gender, height and age) : therefore, the DataFrame has 4 columns.

    The column containing the numbering of the lines is called the index and is not managed in the same way as other columns of the DataFrame.

    The index can be set by default (will follow the row numbering), defined with one (or several) of the columns of the DataFrame or even defined with a list that we specify.

    Example: Default indexing (line numbering), you don't have to specify anything :
    	Name 	Gender 	Height 	Age
    0 	Robert 	M 	174 	23
    1 	Mark 	M 	182 	40
    2 	Aline 	F 	169 	56

    Example: Indexing by the column 'Name':
    	Gender 	Height 	Age
    Robert 	M 	174 	23
    Mark 	M 	182 	40
    Aline 	F 	169 	56

    Example: Indexing by the list ['person_1', 'person_2', 'person_3']:
    	Name 	Gender 	Height 	Age
    person_1 	Robert 	M 	174 	23
    person_2 	Mark 	M 	182 	40
    person_3 	Aline 	F 	169 	56

    We will detail later how to define the index when creating a DataFrame.

    The DataFrame class has several advantages over aNumpy array:

            Visually, a DataFrame is much more readable thanks to more explicit column and row indexing.

            Within the same column the elements are of the same type but from one column to another, the type of the elements may vary, which is not the case of Numpy arrays which only support data of the same type.

            The DataFrame class contains more methods for handling and preprocessing databases, while NumPy specializes instead in optimized computation.



## Creation of a DataFrame: from a NumPy array

In [ ]:
2. Creation of a DataFrame: from a NumPy array

    It is possible to directly create a DataFrame from a NumPy array using the DataFrame() constructor. The disadvantage of this method is that it is not very practical and the data type is necessarily the same for all the columns.

    Let's take a closer look at the header of this constructor.

    pd.DataFrame(data, index, columns, ...)

            The data parameter contains the data to be formatted (NumPy array, list, dictionary or another DataFrame).

            The index parameter, if specified, must be a list containing the indices of the entries.

            The columns parameter, if specified, must be a list containing the name of the columns.

    For other parameters, you can consult the Python documentation.

    Example:

    # Creation of a NumPy array with 3 rows and 4 columns
    array = np.array ([[1, 2, 3, 4],
                       [5, 6, 7, 8],
                       [9, 10, 11, 12]])

    # Instantiation of a DataFrame
    df = pd.DataFrame (data = array, # The data to format
                       index = ['i_1', 'i_2', 'i_3'], # The indices of each entry
                       columns = ['A', 'B', 'C', 'D']) # The name of the columns

    This produces the following DataFrame:
    	A 	B 	C 	D
    i_1 	1 	2 	3 	4
    i_2 	5 	6 	7 	8
    i_3 	9 	10 	11 	12

## Creation of a DataFrame: from a dictionary

In [ ]:
3. Creation of a DataFrame: from a dictionary

    Another way to create a DataFrame is to use a dictionary. Thanks to this technique, the columns can be of different type and their names are already given when creating the DataFrame.

    Example:

    # Creation of a dictionary
    dictionary = {'A': [1, 5, 9],
                  'B': [2, 6, 10],
                  'C': [3, 7, 11],
                  'D': [4, 8, 12]}

    # Instantiation of a DataFrame
    df = pd.DataFrame (data = dictionary,
                       index = ['i_1', 'i_2', 'i_3'])

    This produces the same DataFrame as before:
    	A 	B 	C 	D
    i_1 	1 	2 	3 	4
    i_2 	5 	6 	7 	8
    i_3 	9 	10 	11 	12

The manager of a grocery store has the following stock of food products:

    100 jars of honey with an expiration date of 08/10/2025 and worth €2 each.

    55 packets of flour expiring on 09/25/2024 each costing € 3.

    1800 bottles of wine costing € 10 per unit and expiring on 10/15/2023.

    (a) From a dictionary, create and display a DataFrame df that contains for each product:

            Its name.
            Its expiration date.
            Its quantity.
            Its price per unit.

You will choose relevant column names and the index will be the default one (in this case we do not specify the index parameter).

In [42]:
# Insert your Code

dictionary = {"Product"          : ['honey', 'flour', 'wine'],
              "Expiration date"  : ['10/08/2025', '25/09/2024', '15/10/2023'],
              "Quantity"         : [100, 55, 1800], 
              "Price per unit"   : [2, 3, 10]}

df = pd.DataFrame(dictionary)

df

Product Expiration date  Quantity  Price per unit
0   honey      10/08/2025       100               2
1   flour      25/09/2024        55               3
2    wine      15/10/2023      1800              10

## Creation of a DataFrame: from a data file

In [ ]:
4. Creation of a DataFrame: from a data file

    Most often a DataFrame is created directly from a file containing the data of interest. The file's format can be a CSV, Excel, txt, etc.

    The most common format is the CSV format, which stands for Comma-Separated Values and denotes a spreadsheet-like file whose values are separated by commas.

    Here is an example:

    A, B, C, D,
    1, 2, 3, 4,
    5, 6, 7, 8,
    9, 10, 11, 12

    In this format:

            The first line contains the name of the columns, but sometimes the name of the columns is not filled in.

            Each line corresponds to an entry in the database.

            The values are separated by a separator character. In this example, it is ',' but it could be a ';'.

    To import the data into a DataFrame, we need to use the read_csv function of pandas whose header is as follows:

    pd.read_csv(filepath_or_buffer, sep = ',', header = 0, index_col = 0 ...)

    The essential arguments of the pd.read_csv function to know are:

            filepath_or_buffer: The path of the .csv file relative to the execution environment.
                If the file is in the same folder as the Python environment, just fill in the name of the file.
                This path must be entered in the form of character string.

            sep: The character used in the .csv file to to separate the different columns.
                This argument must be specified as character.

            header: The number of the row that contains the names of the columns.
                If for example the column names are entered in the first line of the .csv file, then we must specify header = 0.
                If the names are not included, we will put header = None.

            index_col: The name or number of the column containing the indices of the database.
                If the database entries are indexed by the first column, you will need to fill in index_col = 0.
                Alternatively, if the entries are indexed by a column which bears the name "Id", we can specify index_col = "Id".

    This function will return an object of type DataFrame which contains all the data of the file.

    (a) Load the data contained in the file transactions.csv into aDataFrame named transactions:

            The file is located in the same folder as the environment of this notebook.
            Columns are separated by commas.
            The names of the columns are in the first line of the file.
            The rows of the database are indexed by the "transaction_id" column which is also the first column.



In [ ]:
# insert your code

# You can directly specify the name of the column containing the indices

transactions = pd.read_csv(filepath_or_buffer = 'transactions.csv', # file path
                           sep = ',',                               # character separating values
                           header = 0,                              # number of the row containing column names
                           index_col = 'transaction_id')            # name of the column that indexes the entries


# You can also directly enter the number of the column that indexes the entries

transactions = pd.read_csv(filepath_or_buffer = 'transactions.csv',
                           sep = ',',
                           header = 0,
                           index_col = 0) # number of the column that indexes the entries

# We loaded the transactions.csv file in theDataFrame transactions which gathers a history of transactions carried out between 2011 and 2014. 
#In the next section, we will study this dataset.

## First exploration of a dataset using the DataFrame class

In [ ]:
5. First exploration of a dataset using the DataFrame class

    The rest of this notebook briefly presents the main methods of the DataFrame class which will allow us to do a quick analysis of our data set, that is:

            Having a brief overview of the data (head method,columns and shape attributes).

            Selecting values in the DataFrame (loc and iloc methods).

            Carrying out a quick statistical study of our data (describe and value _counts methods)

    As a reminder, to apply a method to an object in Python (such as a DataFrame for example), you must add the method as a suffix of the object. Example: my_object.my_method()


## Visualization of a DataFrame: head method, columns and shape attributes

In [ ]:
6. Visualization of a DataFrame: head method, columns and shape attributes

        It is possible to have a preview of a dataset by displaying only the first lines of the DataFrame.

    For that, we must use the head() method, specifying as an argument the number of lines that we want to display (by default 5).

    It is also possible to preview the last lines using the tail() method which is applied in the same way:

    # Display of the first 10 lines of my_dataframe
    my_dataframe.head(10)

    (a) Display the first 20 lines of the transactions DataFrame.


In [ ]:
# Insert your code here
transactions.head(20)

In [ ]:
# (b) Display the last 10 lines of the transactions DataFrame.

In [ ]:
# Insert your code here
transactions.tail(10)

In [ ]:
     	A 	B 	C 	D
    i_ 1 	1 	2 	3 	4
    i _2 	5 	6 	7 	8
    i_ 3 	9 	10 	11 	12

    # Display of df DataFrame columns
    print(df.columns)
    >>> ['A', 'B', 'C', 'D']

    The list of the column names can be used to iterate over the columns of a DataFrame within a loop.

    It can be interesting to know how many transactions (rows) and how many features (columns) the dataset contains.

    For this we will use the shape attribute of the DataFrame class which displays the dimensions of our DataFrame in the form of a tuple (number of rows, number of columns):

    # Display the dimensions of df
    print (df.shape)
    >>> (3,4)

    (c) Display the dimensions of the DataFrame transactions as well as the name of the 5th column. Remember that in Python the indices start from 0.


In [ ]:
# Insert your code here
print(transactions.shape)

transactions.columns[4]

## Selecting columns from a DataFrame

In [ ]:
7. Selecting columns from a DataFrame

    Extracting columns from a DataFrame is almost identical to extracting data from a dictionary.

    To extract a column from a DataFrame, all we have to do is enter between brackets the name of the column to extract. To extract several columns, we must enter between brackets the list of the names of the columns to extract:

    # Display of the 'cust_id' column
    print(transactions['cust_id'])

    # Extraction of 'cust_id' and 'Qty' columns from transactions
    cust_id_qty = transactions[["cust_id", "Qty"]]

    cust_id_qty is a new DataFrame containing only the 'cust_id' and 'Qty' columns.

    The display of the first 3 lines of cust_id_qty yields:



    transactions_id 	cust_id 	Qty
    80712190438 	270351 	-5
    29258453508 	270384 	-5
    51750724947 	273420 	-2

    When we prepare a dataset for later use, it is better to separate the categorical variables from the quantitative variables:

            A categorical variable is a variable that takes only a finite number of modalities.

            The categorical variables of the DataFrame transactions are: ['cust_id', 'tran_date', 'prod_subcat_code', 'prod_cat_code', 'Store_type'].

            A quantitative variable is a variable that measures a quantity that can take an infinite number of values.

            The quantitative variables of transactions are: ['Qty', 'Rate', 'Tax', 'total_amt'].

    This distinction is made because some basic operations like calculating an average only make sense for quantitative variables.

    (a) In a DataFrame named cat_vars, store the categorical variables of transactions.

    (b) In a DataFrame named num_vars, store the quantitative variables of transactions.

    (c) Display the first 5 lines of each DataFrame.



In [ ]:
# insert your code

# Extraction of categorical variables
cat_var_names = ['cust_id', 'tran_date', 'prod_subcat_code', 'prod_cat_code' , 'Store_type']
cat_vars = transactions[cat_var_names]

# Extraction of quantitative variables
num_var_names = ['Qty', 'Rate', 'Tax', 'total_amt']
num_vars = transactions[num_var_names]

# Display of the first 5 lines of each DataFrame
print ("Categorical variables: \n")
print (cat_vars.head(), "\n \n")

print ("Quantitative variables: \n")
print (num_vars.head())

## Selecting rows of a DataFrame: loc and iloc methods

In [ ]:
8. Selecting rows of a DataFrame: loc and iloc methods

    To extract one or more rows from a DataFrame, we use the loc method. loc is a very special type of method because the arguments are filled in between square brackets and not between parentheses. Using this method is very similar to indexing lists.

    In order to retrieve the line of index i of a DataFrame, all we have to do is enter i as an argument of the loc method:

    # We retrieve the line of index 80712190438 of the num_vars DataFrame
    print(num_vars.loc[80712190438])

    >>                 Rate    Tax  total_amt
    >> transaction_id                         
    >> 80712190438    -772.0  405.3    -4265.3
    >> 80712190438     772.0  405.3     4265.3

    In order to retrieve several rows, we can either:

            Enter a list of indices.

            Enter a slice by specifying the start and end indices of the slice. To use slicing with loc, the indices must be unique, which is not the case for transactions.

    # We retrieve the rows at indices 80712190438, 29258453508 and 51750724947 from the transactions DataFrame
    transactions.loc[[80712190438, 29258453508, 51750724947]]

    loc can also take a column or list of columns as an argument in order to refine the data extraction:

    # We extract the columns 'Tax' and 'total_amt' from the rows at index 80712190438 and 29258453508
    transactions.loc[[80712190438, 29258453508], ['Tax', 'total_amt']]

    This instruction produces the following DataFrame:



    transaction_id 	Tax 	total_amt
    80712190438 	405.300 	-4265.300
    80712190438 	405.300 	4265.300
    29258453508 	785.925 	-8270.925
    29258453508 	785.925 	8270.925

    The iloc method is used to index a DataFrame exactly like a numpy array, that is to say by only filling in the numeric indices of the rows and columns. This allows the use of slicing without constraint:

    # Extraction of the first 4 rows and the first 3 columns of transactions
    transactions.iloc[0:4, 0:3]

    This instruction produces the following DataFrame:



    transaction_id 	cust_id 	tran_date 	prod_subcat_code
    80712190438 	270351 	28-02-2014 	1.0
    29258453508 	270384 	27-02-2014 	5.0
    51750724947 	273420 	24-02-2014 	6.0
    93274880719 	271509 	24-02-2014 	11.0

    If the row indexing is the one by default (row numbering), the loc and iloc methods are equivalent.





## Conditional indexing of a DataFrame

In [ ]:
9. Conditional indexing of a DataFrame

    As with Numpy arrays, we can use conditional indexing to extract rows from a Dataframe that meet a given condition.

    In the following illustration, we select the rows of the DataFrame df for which the column col 2 is equal to 3.


    There are two syntaxes for conditionally indexing a DataFrame:


    # We select the rows of the DataFrame df for which the column 'col 2' is equal to 3.
    df[df['col 2'] == 3]

    df.loc[df['col 2'] == 3]

    If we want to assign a new value to these entries, we must absolutely use the loc method.

    Indeed, indexing with the syntax df[df['col 2'] == 3] only returns a copy of these entries and does not provide access the memory location where the data is located.

The manager of the transactions listed in the transactions DataFrame wishes to have access to the identifiers of customers who have made an online purchase (i.e. in a "e-Shop") as well as the date of the corresponding transaction.

We have the following information about the columns of transactions:
Column name 	Description
'cust_id' 	The identifier of the customer
'Store_type' 	The type of store where the transaction took place
'tran_date' 	The date of the transaction

    (a) In a DataFrame named transactions_eshop, store the transactions that took place in an "e-Shop" type store.

    (b) In another DataFrame named transactions_id_date, store the customer identifiers and the transaction date of the transactions_eshop DataFrame.

    (c) Display the first 5 rows of transactions_id_date.

In [ ]:
# insert your code

# Creation of transactions_eshop by conditional indexing
transactions_eshop = transactions.loc[transactions['Store_type'] == 'e-Shop']

# Extraction of the 'cust_ id' and 'tran _date' columns
transactions_id_date = transactions_eshop[['cust_id', 'tran_date']]

# Display of the first 5 lines of transactions_id_date
transactions_id_date.head()

In [ ]:
Now, the manager would like to have access to the transactions carried out by the client whose identifier is 268819.

    (d) In a DataFrame named transactions_client_268819, store all transactions with client identifier 268819.

    (e) A column in a DataFrame can be iterated over with a loop exactly like a list (for value in df['column']:). Using a for loop on the 'total_amt' column, compute and display the total transaction amount for the client with identifier 268819.



In [ ]:
# Insert your code here

# Extraction of the transactions ofthe customer which identifier is 268819
transactions_client_268819 = transactions[transactions['cust_id'] == 268819]


# Computation of the total amount of transactions
total = 0

# For each amount in the column 'total_amt'
for amount in transactions_client_268819['total_amt']:
    # We sum the amounts
    total += amount
    
print(total)

# Second Way
transactions.loc[transactions.cust_id == 268819]['total_amt'].sum()

## Quick statistical study of the data in a DataFrame.

In [ ]:
10. Quick statistical study of the data in a DataFrame.

    The describe method of a DataFrame returns a summary of the descriptive statistics (min, max, mean, quantiles,...) of its quantitative variables. It is therefore a very useful tool for a first visualisation of the type and distribution of these variables.

    To analyse the categorical variables, it is recommended to start by using the value_counts method which returns the number of occurrences for each modality of these variables. The value_counts method cannot be used directly on a DataFrame but only on the columns of the DataFrame which are objects of the pd.Series class.

    (a) Use the describe method of the DataFrame transactions.

    (b) The quantitative variables of transactions are 'Qty', 'Rate', 'Tax' and total_amt'. By default, are the statistics produced by the describe method only computed on the quantitative variables?

    (c) Display the number of occurrences of each modality of the Store_type column using the value_counts method.



In [ ]:
# Insert your code here

transactions.describe()

transactions['Store_type'].value_counts()

In [ ]:


    The describe method computed statistics on the variables cust_id, prod_subcat_code and prod_cat_code while these are categorical variables.

    Of course, these statistics make no sense. The describe method has treated these variables as quantitative because the modalities they take are of numerical type.

    This is why it is necessary to pay attention to the results returned by the describe method and always take a step back to remember what the variables are reflecting.

    The manager wishes to make a quick report on the characteristics of the transactions DataFrame: in particular, he wants to know the average amount spent as well as the maximum quantity purchased.

    (d) What is the average total amount spent? We are interested in the 'total_amt' column of transactions.

    (e) What is the maximum quantity purchased? We will look at the 'Qty' column of transactions.



In [ ]:
# Insert your code here

print('average total amount spent :', transactions['total_amt'].mean())
print('maximum quantity purchased :', transactions['Qty'].max())

transactions.describe()

# Applying the describe method to the transactions DataFrame
transactions.describe()

# The average total amount spent is €2109.
# The maximum quantity purchased is 5. 

In [ ]:
Some transactions have negative amounts.

These are transactions that have been cancelled and refunded to the client. These amounts will disrupt the distribution of the amounts which gives us bad estimates of the mean and quantiles of the variable total_amt.

    (f) What is the average amount of transactions with positive amounts?



In [ ]:
# insert your code here

transactions[transactions['total_amt'] > 0].describe()

# the average amount of transactions with positive amounts is worth €2608 which is
# €500 more than we had before.

## Conclusion and recap

In [ ]:
11. Conclusion and recap

    The DataFrame class of the pandas module will be your favorite data structure when exploring, analysing and processing datasets and databases.

    In this brief introduction, you have learned to:

            Create a DataFrame from a numpy array and a dictionary using the pd.DataFrame constructor.

            Create a DataFrame from a .csv file using the pd.read_csv function.

            Display the first and last lines of a DataFrame using the head and tail methods.

            Select one or more columns of a DataFrame by entering their names in square brackets as in a dictionary.

            Select one or more lines of a DataFrame by filling in their index using the loc and iloc methods.

            Select the lines of a DataFrame that meet a specific condition using conditional indexing.

            Perform a quick statistical study of the quantitative variables of a DataFrame using the describe method.

    The dataset transactions we used is very clean. The variables are cleanly filled in and do not contain any missing value. In practice, this is rarely the case. This is why in the following notebook we will see how to clean datasets with pandas.



In [ ]:
import numpy as np

#e)
df_first = df.drop_duplicates(keep = 'first')
df_repStore = df_first.replace(['e-Shop', 'TeleShop', 'MBR', 'Flagship store', np.nan], [1, 2, 3, 4, 0])
df_repStore.head().dtypes

#f)
dict1 = {'Store_type' : 'int',
        'prod_subcat_code' : 'int'}

df_repStore.astype(dict1).dtypes
df_repStore.dtypes

In [56]:
dict1 = {'name' : ['Brown', 'Duch', 'Hana', 'Brown'],
         'country' : ['Aus', 'Fra', 'De', 'Aus'],
         'age' : [33, 25, 38, 33]}

df = pd.DataFrame(dict1)
df

name country  age
0  Brown     Aus   33
1   Duch     Fra   25
2   Hana      De   38
3  Brown     Aus   33

In [58]:
df_first = df.drop_duplicates()
df_first
df_first.dtypes

name       object
country    object
age         int64
dtype: object

In [59]:
print(df_first.dtypes)

dict1 = {'age' :'object'}

df_first.astype(dict1).dtypes


name       object
country    object
age         int64
dtype: object


name       object
country    object
age        object
dtype: object

In [60]:
df_first.dtypes

name       object
country    object
age         int64
dtype: object